import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  shell: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  header: {
    borderBottomWidth: 1,
    borderBottomColor: "#242b35",
    paddingHorizontal: 14,
    paddingTop: 6,
    paddingBottom: 7,
    gap: 6,
    backgroundColor: "#10151d",
  },
  content: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  productScreen: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  productHeader: {
    borderBottomWidth: 1,
    borderBottomColor: "#242b35",
    backgroundColor: "#10151d",
    paddingHorizontal: 14,
    paddingTop: 7,
    paddingBottom: 8,
    gap: 6,
  },
  productHeaderTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  productHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  productEyebrow: {
    color: "#8390a3",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  productHeaderTitle: {
    color: "#f4f8ff",
    fontSize: 19,
    fontWeight: "900",
  },
  productHeaderSummary: {
    color: "#9da8b8",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
  },
  productChangeButton: {
    minHeight: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#3c82ad",
    backgroundColor: "#102a3d",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 11,
  },
  productChangeText: {
    color: "#d4efff",
    fontSize: 12,
    fontWeight: "900",
  },
  productRefreshButton: {
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#36465a",
    backgroundColor: "#1a2532",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  productRefreshText: {
    color: "#eaf2fb",
    fontSize: 12,
    fontWeight: "900",
  },
  productPickerRow: {
    gap: 7,
    paddingRight: 6,
  },
  productPickerChip: {
    maxWidth: 220,
    minHeight: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2d3847",
    backgroundColor: "#121820",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  productPickerChipActive: {
    borderColor: "#4aa3d8",
    backgroundColor: "#123149",
  },
  productPickerText: {
    color: "#9ca8ba",
    fontSize: 12,
    fontWeight: "900",
  },
  productPickerTextActive: {
    color: "#eef8ff",
  },
  productModalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.58)",
  },
  productModal: {
    maxHeight: "72%",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderWidth: 1,
    borderColor: "#2f3948",
    backgroundColor: "#10151d",
    paddingTop: 14,
  },
  productModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#242b35",
  },
  productModalTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  productModalTitle: {
    color: "#f4f8ff",
    fontSize: 18,
    fontWeight: "900",
  },
  productModalMeta: {
    color: "#8f9caf",
    fontSize: 12,
    fontWeight: "800",
  },
  productModalClose: {
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#384657",
    backgroundColor: "#172231",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  productModalCloseText: {
    color: "#eaf2fb",
    fontSize: 12,
    fontWeight: "900",
  },
  productModalList: {
    padding: 12,
    gap: 8,
  },
  productModalRow: {
    minHeight: 76,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2f3948",
    backgroundColor: "#111820",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 12,
  },
  productModalRowActive: {
    borderColor: "#4aa3d8",
    backgroundColor: "#123149",
  },
  productModalRowCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  productModalRowTitle: {
    color: "#f4f8ff",
    fontSize: 15,
    fontWeight: "900",
  },
  productModalRowSummary: {
    color: "#98a5b7",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  productModalRowStatus: {
    color: "#9fcaf0",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  productStatsRow: {
    flexDirection: "row",
    gap: 8,
  },
  productStat: {
    flex: 1,
    minHeight: 58,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2f3948",
    backgroundColor: "#121820",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  productStatValue: {
    color: "#f4f8ff",
    fontSize: 18,
    fontWeight: "900",
  },
  productStatLabel: {
    color: "#8f9caf",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
    marginTop: 3,
  },
  productModeRow: {
    flexDirection: "row",
    gap: 6,
    minHeight: 32,
  },
  productModeButton: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2f3948",
    backgroundColor: "#121820",
    alignItems: "center",
    justifyContent: "center",
  },
  productModeButtonActive: {
    borderColor: "#2f8fc8",
    backgroundColor: "#123149",
  },
  productModeText: {
    color: "#9ca8ba",
    fontSize: 12,
    fontWeight: "900",
  },
  productModeTextActive: {
    color: "#eef8ff",
  },
  productListContent: {
    padding: 12,
    gap: 9,
  },
  productRootHeader: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  productRootTitle: {
    color: "#f4f8ff",
    fontSize: 15,
    fontWeight: "900",
  },
  productRootMeta: {
    color: "#8f9caf",
    fontSize: 11,
    fontWeight: "800",
  },
  productContextPanel: {
    borderWidth: 1,
    borderColor: "#2f3948",
    borderRadius: 8,
    backgroundColor: "#111820",
    padding: 11,
    gap: 7,
  },
  productBreadcrumbRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 28,
  },
  productBackButton: {
    minHeight: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#36465a",
    backgroundColor: "#172231",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  productBackText: {
    color: "#eaf2fb",
    fontSize: 12,
    fontWeight: "900",
  },
  productPathLine: {
    flex: 1,
    color: "#8895a8",
    fontSize: 12,
    fontWeight: "800",
  },
  productContextTitle: {
    color: "#f4f8ff",
    fontSize: 19,
    lineHeight: 23,
    fontWeight: "900",
  },
  productContextSummary: {
    color: "#a4afbf",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  productPlannerPanel: {
    borderWidth: 1,
    borderColor: "#334154",
    borderRadius: 8,
    backgroundColor: "#0e141c",
    padding: 10,
    gap: 8,
  },
  productPlannerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  productPlannerCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  productPlannerTitle: {
    color: "#f4f8ff",
    fontSize: 13,
    fontWeight: "900",
  },
  productPlannerStatus: {
    color: "#8f9caf",
    fontSize: 11,
    fontWeight: "800",
  },
  productPlannerIconButton: {
    minHeight: 30,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#384657",
    backgroundColor: "#172231",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  productPlannerIconText: {
    color: "#eaf2fb",
    fontSize: 11,
    fontWeight: "900",
  },
  productPlannerInput: {
    minHeight: 46,
    maxHeight: 90,
    borderWidth: 1,
    borderColor: "#2f3948",
    borderRadius: 8,
    backgroundColor: "#111820",
    color: "#f4f8ff",
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  productPlannerActions: {
    flexDirection: "row",
    gap: 8,
  },
  productPlannerAction: {
    flex: 1,
    minHeight: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#39485c",
    backgroundColor: "#1a2330",
    alignItems: "center",
    justifyContent: "center",
  },
  productPlannerActionRecording: {
    borderColor: "#d65f5f",
    backgroundColor: "#8d3030",
  },
  productPlannerActionPrimary: {
    borderColor: "#2f8fc8",
    backgroundColor: "#123149",
  },
  productPlannerActionText: {
    color: "#eaf2fb",
    fontSize: 12,
    fontWeight: "900",
  },
  productPlannerPrimaryText: {
    color: "#eef8ff",
    fontSize: 12,
    fontWeight: "900",
  },
  productPlannerReply: {
    color: "#b9c6d8",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  productPlannerTraceList: {
    gap: 4,
  },
  productPlannerTraceItem: {
    color: "#85c9f5",
    fontSize: 10,
    fontWeight: "900",
  },
  productNodeRow: {
    borderWidth: 1,
    borderColor: "#2f3948",
    borderRadius: 8,
    backgroundColor: "#111820",
    padding: 12,
  },
  productNodeMain: {
    gap: 8,
  },
  productNodeTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  productNodeTitle: {
    flex: 1,
    color: "#f4f8ff",
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "900",
  },
  productNodeChevron: {
    color: "#92cff5",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
    marginTop: 3,
  },
  productNodePath: {
    color: "#748296",
    fontSize: 11,
    fontWeight: "800",
  },
  productNodeSummary: {
    color: "#a6b0c0",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  productNodeMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 7,
  },
  productKindBadge: {
    overflow: "hidden",
    borderRadius: 8,
    backgroundColor: "#203149",
    color: "#b9d4f2",
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: "900",
  },
  productNodeMeta: {
    color: "#8e9bad",
    fontSize: 11,
    fontWeight: "800",
  },
  productSearchScreen: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  productSearchInput: {
    marginHorizontal: 14,
    marginTop: 14,
    marginBottom: 4,
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#354253",
    backgroundColor: "#121820",
    color: "#f4f8ff",
    paddingHorizontal: 12,
    fontSize: 14,
    fontWeight: "700",
  },
  productSearchCount: {
    color: "#8f9caf",
    fontSize: 12,
    fontWeight: "900",
    marginBottom: 2,
  },
  productOverviewScreen: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  productOverviewCard: {
    borderWidth: 1,
    borderColor: "#2f3948",
    borderRadius: 8,
    backgroundColor: "#111820",
    padding: 12,
    gap: 8,
  },
  productOverviewTitle: {
    color: "#f4f8ff",
    fontSize: 16,
    fontWeight: "900",
  },
  productOverviewText: {
    color: "#a6b0c0",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  productOverviewGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  productOverviewMetric: {
    width: "48%",
    minHeight: 72,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2f3948",
    backgroundColor: "#111820",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  productTagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  productEmptyScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0d1015",
    padding: 22,
    gap: 12,
  },
  productEmptyBlock: {
    borderWidth: 1,
    borderColor: "#2f3948",
    borderRadius: 8,
    backgroundColor: "#111820",
    padding: 14,
    gap: 6,
  },
  productEmptyTitle: {
    color: "#f4f8ff",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "center",
  },
  productEmptyText: {
    color: "#9ca8ba",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
    textAlign: "center",
  },
  productPrimaryAction: {
    minHeight: 42,
    borderRadius: 8,
    backgroundColor: "#0e639c",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  productPrimaryActionText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "900",
  },
  voiceScreen: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  voiceTopBand: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
  },
  voiceTopCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  voiceTitle: {
    color: "#f4f8ff",
    fontSize: 22,
    fontWeight: "900",
  },
  voiceSubtitle: {
    color: "#9ba8ba",
    fontSize: 12,
    fontWeight: "700",
  },
  runtimeChip: {
    maxWidth: 190,
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2f8fc8",
    backgroundColor: "#10293a",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  runtimeChipText: {
    color: "#b9e4ff",
    fontSize: 11,
    fontWeight: "900",
  },
  voiceModeRow: {
    flexDirection: "row",
    gap: 7,
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  voiceModeButton: {
    flex: 1,
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2f3948",
    backgroundColor: "#121820",
    alignItems: "center",
    justifyContent: "center",
  },
  voiceModeButtonActive: {
    borderColor: "#2f8fc8",
    backgroundColor: "#123149",
  },
  voiceModeText: {
    color: "#9ca8ba",
    fontSize: 12,
    fontWeight: "900",
  },
  voiceModeTextActive: {
    color: "#eef8ff",
  },
  voiceConversation: {
    flex: 1,
  },
  voiceConversationContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 12,
    gap: 12,
  },
  voiceBubble: {
    maxWidth: "86%",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  voiceBubbleAssistant: {
    alignSelf: "flex-start",
    backgroundColor: "#202733",
    borderTopLeftRadius: 3,
  },
  voiceBubbleUser: {
    alignSelf: "flex-end",
    backgroundColor: "#0e639c",
    borderTopRightRadius: 3,
  },
  voiceBubbleText: {
    fontSize: 15,
    lineHeight: 22,
  },
  voiceBubbleTextAssistant: {
    color: "#eef4fb",
  },
  voiceBubbleTextUser: {
    color: "#ffffff",
  },
  plannerTraceList: {
    gap: 7,
    marginTop: 10,
  },
  plannerTraceCard: {
    borderWidth: 1,
    borderColor: "#354457",
    borderRadius: 8,
    backgroundColor: "#151c26",
    padding: 9,
    gap: 5,
  },
  plannerTraceHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  plannerTraceTitle: {
    flex: 1,
    color: "#d9eaff",
    fontSize: 11,
    fontWeight: "900",
  },
  plannerTraceStatus: {
    color: "#76dbac",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  plannerTraceStatusError: {
    color: "#ff9c9c",
  },
  plannerTraceMeta: {
    color: "#9aa8bd",
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "700",
  },
  voiceComposerPanel: {
    marginHorizontal: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#2f3948",
    borderRadius: 24,
    backgroundColor: "#111820",
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 10,
    gap: 8,
  },
  voiceComposerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingHorizontal: 4,
  },
  voiceComposerLabel: {
    flex: 1,
    color: "#e8eef7",
    fontSize: 13,
    fontWeight: "900",
  },
  voiceComposerStatus: {
    maxWidth: 178,
    color: "#8fa0b6",
    fontSize: 11,
    fontWeight: "800",
  },
  voiceComposerInput: {
    minHeight: 50,
    maxHeight: 112,
    color: "#f4f8ff",
    fontSize: 16,
    lineHeight: 22,
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  voiceComposerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 42,
  },
  voiceClearButton: {
    minWidth: 68,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: "#344052",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#151c26",
    paddingHorizontal: 12,
  },
  voiceClearButtonText: {
    color: "#c5d0df",
    fontSize: 13,
    fontWeight: "900",
  },
  voiceComposerSpacer: {
    flex: 1,
  },
  voiceMicButton: {
    minWidth: 58,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1a2330",
    borderWidth: 1,
    borderColor: "#39485c",
  },
  voiceMicButtonRecording: {
    backgroundColor: "#b33939",
    borderColor: "#d65f5f",
  },
  voiceMicButtonText: {
    color: "#eaf2fb",
    fontSize: 13,
    fontWeight: "900",
  },
  voiceSendButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  voiceSendButtonText: {
    color: "#0d1015",
    fontSize: 25,
    lineHeight: 28,
    fontWeight: "900",
  },
  voiceControlHint: {
    paddingHorizontal: 4,
    color: "#9ba8ba",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
  },
  callsScreen: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  callsHeader: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#222a35",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  callsTitle: {
    color: "#f4f8ff",
    fontSize: 22,
    fontWeight: "900",
  },
  callsSubtitle: {
    color: "#8e9aad",
    fontSize: 12,
    marginTop: 3,
    fontWeight: "700",
  },
  callsRefreshButton: {
    borderWidth: 1,
    borderColor: "#38506a",
    backgroundColor: "#132235",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  callsRefreshText: {
    color: "#dcecff",
    fontSize: 12,
    fontWeight: "900",
  },
  callsError: {
    color: "#ff9b9b",
    fontSize: 12,
    fontWeight: "700",
    paddingHorizontal: 16,
    paddingTop: 10,
  },
  callsBody: {
    flex: 1,
  },
  callsBodyContent: {
    padding: 12,
    gap: 10,
  },
  callRow: {
    borderWidth: 1,
    borderColor: "#2a333f",
    backgroundColor: "#121820",
    borderRadius: 8,
    padding: 12,
    gap: 5,
  },
  callRowActive: {
    borderColor: "#4c9fda",
    backgroundColor: "#142437",
  },
  callRowTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  callSource: {
    flex: 1,
    color: "#edf5ff",
    fontSize: 13,
    fontWeight: "900",
  },
  callStatus: {
    color: "#6ee7bd",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  callStatusFailed: {
    color: "#ff9b9b",
  },
  callMeta: {
    color: "#a7b3c4",
    fontSize: 12,
    fontWeight: "700",
  },
  callTime: {
    color: "#6f7d90",
    fontSize: 11,
    fontWeight: "700",
  },
  callsEmpty: {
    borderWidth: 1,
    borderColor: "#2a333f",
    backgroundColor: "#121820",
    borderRadius: 8,
    padding: 16,
    gap: 6,
  },
  callsEmptyTitle: {
    color: "#f4f8ff",
    fontSize: 15,
    fontWeight: "900",
  },
  callsEmptyText: {
    color: "#96a3b5",
    fontSize: 12,
    lineHeight: 17,
  },
  callDetailPanel: {
    borderWidth: 1,
    borderColor: "#334052",
    backgroundColor: "#101721",
    borderRadius: 8,
    padding: 12,
    gap: 8,
  },
  callDetailTitle: {
    color: "#f4f8ff",
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 2,
  },
  callSessionStats: {
    flexDirection: "row",
    gap: 8,
  },
  callSessionStat: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#263240",
    backgroundColor: "#121a25",
    borderRadius: 8,
    padding: 9,
  },
  callSessionStatValue: {
    color: "#f4f8ff",
    fontSize: 14,
    fontWeight: "900",
  },
  callSessionStatLabel: {
    color: "#7f8da1",
    fontSize: 9,
    fontWeight: "900",
    textTransform: "uppercase",
    marginTop: 3,
  },
  callSessionCallsTitle: {
    color: "#f4f8ff",
    fontSize: 13,
    fontWeight: "900",
    marginTop: 4,
  },
  callChildRow: {
    borderWidth: 1,
    borderColor: "#273241",
    backgroundColor: "#111820",
    borderRadius: 8,
    padding: 10,
    gap: 4,
  },
  callChildRowActive: {
    borderColor: "#4c9fda",
    backgroundColor: "#142437",
  },
  callDetailRow: {
    borderTopWidth: 1,
    borderTopColor: "#222b36",
    paddingTop: 7,
    gap: 3,
  },
  callDetailLabel: {
    color: "#7f8da1",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  callDetailValue: {
    color: "#dce5f1",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  callErrorPanel: {
    borderWidth: 1,
    borderColor: "#56323a",
    backgroundColor: "#24161b",
    borderRadius: 8,
    padding: 10,
    gap: 5,
  },
  callErrorText: {
    color: "#ffb4b4",
    fontSize: 12,
    lineHeight: 17,
  },
  modelPage: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  modelPageContent: {
    padding: 16,
    gap: 12,
  },
  modelHeader: {
    gap: 6,
  },
  sectionTitle: {
    color: "#f4f8ff",
    fontSize: 22,
    fontWeight: "900",
  },
  sectionText: {
    color: "#a8b3c4",
    fontSize: 13,
    lineHeight: 19,
  },
  runtimePanel: {
    borderWidth: 1,
    borderColor: "#2c3542",
    borderRadius: 8,
    backgroundColor: "#111820",
    padding: 12,
    gap: 10,
  },
  panelLabel: {
    color: "#e7edf7",
    fontSize: 13,
    fontWeight: "800",
  },
  segmentedControl: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#354253",
    borderRadius: 8,
    overflow: "hidden",
    minHeight: 42,
  },
  segmentButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#12161c",
    paddingHorizontal: 8,
  },
  segmentButtonActive: {
    backgroundColor: "#0e639c",
  },
  segmentButtonText: {
    color: "#a8b3c4",
    fontSize: 13,
    fontWeight: "800",
  },
  segmentButtonTextActive: {
    color: "#ffffff",
  },
  modelStatusPanel: {
    borderWidth: 1,
    borderColor: "#2c3542",
    borderRadius: 8,
    backgroundColor: "#111820",
    padding: 12,
    gap: 10,
  },
  modelStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  modelStatusText: {
    flex: 1,
    color: "#a8b3c4",
    fontSize: 12,
    lineHeight: 17,
  },
  progressText: {
    color: "#f4f8ff",
    fontSize: 12,
    fontWeight: "800",
  },
  progressTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: "#252d38",
    overflow: "hidden",
  },
  progressFill: {
    height: 8,
    borderRadius: 4,
    backgroundColor: "#56b6c2",
  },
  modelList: {
    gap: 10,
  },
  modelCard: {
    borderWidth: 1,
    borderColor: "#2c3542",
    borderRadius: 8,
    backgroundColor: "#111820",
    padding: 12,
    gap: 10,
  },
  modelCardSelected: {
    borderColor: "#7bc8ff",
  },
  modelCardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  modelTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  modelTitle: {
    color: "#f4f8ff",
    fontSize: 15,
    fontWeight: "800",
  },
  modelMeta: {
    color: "#90a0b8",
    fontSize: 12,
  },
  installBadge: {
    color: "#9aa8bd",
    borderWidth: 1,
    borderColor: "#425066",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
    fontSize: 11,
    fontWeight: "800",
    overflow: "hidden",
  },
  installBadgeActive: {
    color: "#dafbe1",
    borderColor: "#3b7f55",
    backgroundColor: "#193323",
  },
  modelDescription: {
    color: "#a8b3c4",
    fontSize: 12,
    lineHeight: 17,
  },
  modelActions: {
    flexDirection: "row",
    gap: 8,
  },
  smallButton: {
    minHeight: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#425066",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    backgroundColor: "#18202a",
  },
  smallButtonActive: {
    borderColor: "#7bc8ff",
    backgroundColor: "#203348",
  },
  smallButtonPrimary: {
    backgroundColor: "#0e639c",
    borderColor: "#0e639c",
  },
  smallButtonText: {
    color: "#d9e4f2",
    fontSize: 13,
    fontWeight: "800",
  },
  smallButtonTextActive: {
    color: "#ffffff",
  },
  smallButtonPrimaryText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "800",
  },
  sourceButton: {
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#425066",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#151922",
  },
  sourceButtonText: {
    color: "#d9e4f2",
    fontSize: 13,
    fontWeight: "800",
  },
  nativeVoiceBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#2f3642",
    backgroundColor: "#151922",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  voiceButton: {
    minWidth: 86,
    minHeight: 42,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0e639c",
    paddingHorizontal: 14,
  },
  voiceButtonRecording: {
    backgroundColor: "#b33939",
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  voiceButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
  },
  voiceStatusBlock: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  voiceStatus: {
    color: "#f4f8ff",
    fontSize: 13,
    fontWeight: "800",
  },
  voiceTranscript: {
    color: "#9aa8bd",
    fontSize: 12,
  },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  titleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  title: {
    color: "#f4f8ff",
    fontSize: 21,
    fontWeight: "900",
  },
  url: {
    color: "#9aa8bd",
    fontSize: 12,
    marginTop: 2,
  },
  connectionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  connectionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  connectionDotReady: {
    backgroundColor: "#49c27c",
  },
  connectionDotMissing: {
    backgroundColor: "#d99b35",
  },
  connectionText: {
    color: "#96a4b8",
    fontSize: 11,
    fontWeight: "800",
  },
  setupPanel: {
    gap: 8,
  },
  setupCaption: {
    color: "#8390a3",
    fontSize: 11,
    fontWeight: "700",
  },
  settingsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    borderWidth: 1,
    borderColor: "#2f3948",
    borderRadius: 8,
    backgroundColor: "#121820",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  settingsCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  settingsLabel: {
    color: "#f4f8ff",
    fontSize: 13,
    fontWeight: "900",
  },
  settingsDescription: {
    color: "#95a3b7",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
  },
  input: {
    backgroundColor: "#12161c",
    borderColor: "#364152",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#f4f8ff",
  },
  flexInput: {
    flex: 1,
    minWidth: 0,
  },
  optionalGrid: {
    flexDirection: "row",
    gap: 8,
  },
  actionRow: {
    flexDirection: "row",
    gap: 8,
  },
  button: {
    backgroundColor: "#223040",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  headerButton: {
    minHeight: 36,
    borderRadius: 8,
    justifyContent: "center",
    backgroundColor: "#1d2a38",
    paddingHorizontal: 12,
  },
  buttonText: {
    color: "#edf3ff",
    fontWeight: "900",
    fontSize: 13,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: "#0e639c",
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 15,
  },
  webView: {
    flex: 1,
    backgroundColor: "#101317",
  },
  bottomTabs: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: "#242b35",
    backgroundColor: "#10151d",
    paddingHorizontal: 6,
    paddingTop: 8,
    paddingBottom: 8,
    gap: 4,
  },
  tabItem: {
    flex: 1,
    minHeight: 50,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  tabItemActive: {
    backgroundColor: "#1d2a38",
  },
  tabIndicator: {
    width: 20,
    height: 3,
    borderRadius: 2,
    backgroundColor: "transparent",
  },
  tabIndicatorActive: {
    backgroundColor: "#69c7ff",
  },
  tabText: {
    color: "#94a1b4",
    fontSize: 11,
    fontWeight: "900",
  },
  tabTextActive: {
    color: "#f4f8ff",
  },
  loading: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#101317",
  },
  errorPanel: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 18,
    gap: 10,
    backgroundColor: "#111317",
  },
  errorTitle: {
    color: "#f4f8ff",
    fontSize: 16,
    fontWeight: "700",
  },
  errorText: {
    color: "#9aa8bd",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
  },
});
