import type { ImageStyle, TextStyle, ViewStyle } from "react-native";

export const callStyles = {
  callsScreen: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  callsHeader: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#222a35",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  callsTitle: {
    color: "#f4f8ff",
    fontSize: 22,
    fontWeight: "900",
  },
  callsSubtitle: {
    color: "#8e9aad",
    fontSize: 12,
    marginTop: 3,
    fontWeight: "700",
  },
  callsRefreshButton: {
    borderWidth: 1,
    borderColor: "#38506a",
    backgroundColor: "#132235",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  callsRefreshText: {
    color: "#dcecff",
    fontSize: 12,
    fontWeight: "900",
  },
  callsError: {
    color: "#ff9b9b",
    fontSize: 12,
    fontWeight: "700",
    paddingHorizontal: 16,
    paddingTop: 10,
  },
  callsBody: {
    flex: 1,
  },
  callsBodyContent: {
    padding: 12,
    gap: 10,
  },
  callRow: {
    borderWidth: 1,
    borderColor: "#2a333f",
    backgroundColor: "#121820",
    borderRadius: 8,
    padding: 12,
    gap: 5,
  },
  callRowActive: {
    borderColor: "#4c9fda",
    backgroundColor: "#142437",
  },
  callRowTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  callSource: {
    flex: 1,
    color: "#edf5ff",
    fontSize: 13,
    fontWeight: "900",
  },
  callStatus: {
    color: "#6ee7bd",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  callStatusFailed: {
    color: "#ff9b9b",
  },
  callMeta: {
    color: "#a7b3c4",
    fontSize: 12,
    fontWeight: "700",
  },
  callTime: {
    color: "#6f7d90",
    fontSize: 11,
    fontWeight: "700",
  },
  callsEmpty: {
    borderWidth: 1,
    borderColor: "#2a333f",
    backgroundColor: "#121820",
    borderRadius: 8,
    padding: 16,
    gap: 6,
  },
  callsEmptyTitle: {
    color: "#f4f8ff",
    fontSize: 15,
    fontWeight: "900",
  },
  callsEmptyText: {
    color: "#96a3b5",
    fontSize: 12,
    lineHeight: 17,
  },
  callDetailPanel: {
    borderWidth: 1,
    borderColor: "#334052",
    backgroundColor: "#101721",
    borderRadius: 8,
    padding: 12,
    gap: 8,
  },
  callDetailTitle: {
    color: "#f4f8ff",
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 2,
  },
  callSessionStats: {
    flexDirection: "row",
    gap: 8,
  },
  callSessionStat: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#263240",
    backgroundColor: "#121a25",
    borderRadius: 8,
    padding: 9,
  },
  callSessionStatValue: {
    color: "#f4f8ff",
    fontSize: 14,
    fontWeight: "900",
  },
  callSessionStatLabel: {
    color: "#7f8da1",
    fontSize: 9,
    fontWeight: "900",
    textTransform: "uppercase",
    marginTop: 3,
  },
  callSessionCallsTitle: {
    color: "#f4f8ff",
    fontSize: 13,
    fontWeight: "900",
    marginTop: 4,
  },
  callChildRow: {
    borderWidth: 1,
    borderColor: "#273241",
    backgroundColor: "#111820",
    borderRadius: 8,
    padding: 10,
    gap: 4,
  },
  callChildRowActive: {
    borderColor: "#4c9fda",
    backgroundColor: "#142437",
  },
  callDetailRow: {
    borderTopWidth: 1,
    borderTopColor: "#222b36",
    paddingTop: 7,
    gap: 3,
  },
  callDetailLabel: {
    color: "#7f8da1",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  callDetailValue: {
    color: "#dce5f1",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  callErrorPanel: {
    borderWidth: 1,
    borderColor: "#56323a",
    backgroundColor: "#24161b",
    borderRadius: 8,
    padding: 10,
    gap: 5,
  },
  callErrorText: {
    color: "#ffb4b4",
    fontSize: 12,
    lineHeight: 17,
  },
} satisfies Record<string, ViewStyle | TextStyle | ImageStyle>;
