import type { ImageStyle, TextStyle, ViewStyle } from "react-native";

export const productStyles = {
  productScreen: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  productHeader: {
    borderBottomWidth: 1,
    borderBottomColor: "#242b35",
    backgroundColor: "#10151d",
    paddingHorizontal: 14,
    paddingTop: 7,
    paddingBottom: 8,
    gap: 6,
  },
  productHeaderTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  productHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  productEyebrow: {
    color: "#8390a3",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  productHeaderTitle: {
    color: "#f4f8ff",
    fontSize: 19,
    fontWeight: "900",
  },
  productHeaderSummary: {
    color: "#9da8b8",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
  },
  productChangeButton: {
    minHeight: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#3c82ad",
    backgroundColor: "#102a3d",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 11,
  },
  productChangeText: {
    color: "#d4efff",
    fontSize: 12,
    fontWeight: "900",
  },
  productRefreshButton: {
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#36465a",
    backgroundColor: "#1a2532",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  productRefreshText: {
    color: "#eaf2fb",
    fontSize: 12,
    fontWeight: "900",
  },
  productPickerRow: {
    gap: 7,
    paddingRight: 6,
  },
  productPickerChip: {
    maxWidth: 220,
    minHeight: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2d3847",
    backgroundColor: "#121820",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  productPickerChipActive: {
    borderColor: "#4aa3d8",
    backgroundColor: "#123149",
  },
  productPickerText: {
    color: "#9ca8ba",
    fontSize: 12,
    fontWeight: "900",
  },
  productPickerTextActive: {
    color: "#eef8ff",
  },
  productModalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.58)",
  },
  productModal: {
    maxHeight: "72%",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderWidth: 1,
    borderColor: "#2f3948",
    backgroundColor: "#10151d",
    paddingTop: 14,
  },
  productModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#242b35",
  },
  productModalTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  productModalTitle: {
    color: "#f4f8ff",
    fontSize: 18,
    fontWeight: "900",
  },
  productModalMeta: {
    color: "#8f9caf",
    fontSize: 12,
    fontWeight: "800",
  },
  productModalClose: {
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#384657",
    backgroundColor: "#172231",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  productModalCloseText: {
    color: "#eaf2fb",
    fontSize: 12,
    fontWeight: "900",
  },
  productModalList: {
    padding: 12,
    gap: 8,
  },
  productModalRow: {
    minHeight: 76,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2f3948",
    backgroundColor: "#111820",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 12,
  },
  productModalRowActive: {
    borderColor: "#4aa3d8",
    backgroundColor: "#123149",
  },
  productModalRowCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  productModalRowTitle: {
    color: "#f4f8ff",
    fontSize: 15,
    fontWeight: "900",
  },
  productModalRowSummary: {
    color: "#98a5b7",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  productModalRowStatus: {
    color: "#9fcaf0",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  productStatsRow: {
    flexDirection: "row",
    gap: 8,
  },
  productStat: {
    flex: 1,
    minHeight: 58,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2f3948",
    backgroundColor: "#121820",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  productStatValue: {
    color: "#f4f8ff",
    fontSize: 18,
    fontWeight: "900",
  },
  productStatLabel: {
    color: "#8f9caf",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
    marginTop: 3,
  },
  productModeRow: {
    flexDirection: "row",
    gap: 6,
    minHeight: 32,
  },
  productModeButton: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2f3948",
    backgroundColor: "#121820",
    alignItems: "center",
    justifyContent: "center",
  },
  productModeButtonActive: {
    borderColor: "#2f8fc8",
    backgroundColor: "#123149",
  },
  productModeText: {
    color: "#9ca8ba",
    fontSize: 12,
    fontWeight: "900",
  },
  productModeTextActive: {
    color: "#eef8ff",
  },
  productListContent: {
    padding: 12,
    gap: 9,
  },
  productRootHeader: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  productRootTitle: {
    color: "#f4f8ff",
    fontSize: 15,
    fontWeight: "900",
  },
  productRootMeta: {
    color: "#8f9caf",
    fontSize: 11,
    fontWeight: "800",
  },
  productContextPanel: {
    borderWidth: 1,
    borderColor: "#2f3948",
    borderRadius: 8,
    backgroundColor: "#111820",
    padding: 11,
    gap: 7,
  },
  productBreadcrumbRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 28,
  },
  productBackButton: {
    minHeight: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#36465a",
    backgroundColor: "#172231",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  productBackText: {
    color: "#eaf2fb",
    fontSize: 12,
    fontWeight: "900",
  },
  productPathLine: {
    flex: 1,
    color: "#8895a8",
    fontSize: 12,
    fontWeight: "800",
  },
  productContextTitle: {
    color: "#f4f8ff",
    fontSize: 19,
    lineHeight: 23,
    fontWeight: "900",
  },
  productContextSummary: {
    color: "#a4afbf",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  productPlannerPanel: {
    borderWidth: 1,
    borderColor: "#334154",
    borderRadius: 8,
    backgroundColor: "#0e141c",
    padding: 10,
    gap: 8,
  },
  productPlannerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  productPlannerCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  productPlannerTitle: {
    color: "#f4f8ff",
    fontSize: 13,
    fontWeight: "900",
  },
  productPlannerStatus: {
    color: "#8f9caf",
    fontSize: 11,
    fontWeight: "800",
  },
  productPlannerIconButton: {
    minHeight: 30,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#384657",
    backgroundColor: "#172231",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  productPlannerIconText: {
    color: "#eaf2fb",
    fontSize: 11,
    fontWeight: "900",
  },
  productPlannerInput: {
    minHeight: 46,
    maxHeight: 90,
    borderWidth: 1,
    borderColor: "#2f3948",
    borderRadius: 8,
    backgroundColor: "#111820",
    color: "#f4f8ff",
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  productPlannerActions: {
    flexDirection: "row",
    gap: 8,
  },
  productPlannerAction: {
    flex: 1,
    minHeight: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#39485c",
    backgroundColor: "#1a2330",
    alignItems: "center",
    justifyContent: "center",
  },
  productPlannerActionRecording: {
    borderColor: "#d65f5f",
    backgroundColor: "#8d3030",
  },
  productPlannerActionPrimary: {
    borderColor: "#2f8fc8",
    backgroundColor: "#123149",
  },
  productPlannerActionText: {
    color: "#eaf2fb",
    fontSize: 12,
    fontWeight: "900",
  },
  productPlannerPrimaryText: {
    color: "#eef8ff",
    fontSize: 12,
    fontWeight: "900",
  },
  productPlannerReply: {
    color: "#b9c6d8",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  productPlannerTraceList: {
    gap: 4,
  },
  productPlannerTraceItem: {
    color: "#85c9f5",
    fontSize: 10,
    fontWeight: "900",
  },
  productNodeRow: {
    borderWidth: 1,
    borderColor: "#2f3948",
    borderRadius: 8,
    backgroundColor: "#111820",
    padding: 12,
  },
  productNodeMain: {
    gap: 8,
  },
  productNodeTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  productNodeTitle: {
    flex: 1,
    color: "#f4f8ff",
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "900",
  },
  productNodeChevron: {
    color: "#92cff5",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
    marginTop: 3,
  },
  productNodePath: {
    color: "#748296",
    fontSize: 11,
    fontWeight: "800",
  },
  productNodeSummary: {
    color: "#a6b0c0",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  productNodeMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 7,
  },
  productKindBadge: {
    overflow: "hidden",
    borderRadius: 8,
    backgroundColor: "#203149",
    color: "#b9d4f2",
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: "900",
  },
  productNodeMeta: {
    color: "#8e9bad",
    fontSize: 11,
    fontWeight: "800",
  },
  productSearchScreen: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  productSearchInput: {
    marginHorizontal: 14,
    marginTop: 14,
    marginBottom: 4,
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#354253",
    backgroundColor: "#121820",
    color: "#f4f8ff",
    paddingHorizontal: 12,
    fontSize: 14,
    fontWeight: "700",
  },
  productSearchCount: {
    color: "#8f9caf",
    fontSize: 12,
    fontWeight: "900",
    marginBottom: 2,
  },
  productOverviewScreen: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  productOverviewCard: {
    borderWidth: 1,
    borderColor: "#2f3948",
    borderRadius: 8,
    backgroundColor: "#111820",
    padding: 12,
    gap: 8,
  },
  productOverviewTitle: {
    color: "#f4f8ff",
    fontSize: 16,
    fontWeight: "900",
  },
  productOverviewText: {
    color: "#a6b0c0",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  productOverviewGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  productOverviewMetric: {
    width: "48%",
    minHeight: 72,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2f3948",
    backgroundColor: "#111820",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  productTagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  productEmptyScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0d1015",
    padding: 22,
    gap: 12,
  },
  productEmptyBlock: {
    borderWidth: 1,
    borderColor: "#2f3948",
    borderRadius: 8,
    backgroundColor: "#111820",
    padding: 14,
    gap: 6,
  },
  productEmptyTitle: {
    color: "#f4f8ff",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "center",
  },
  productEmptyText: {
    color: "#9ca8ba",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
    textAlign: "center",
  },
  productPrimaryAction: {
    minHeight: 42,
    borderRadius: 8,
    backgroundColor: "#0e639c",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  productPrimaryActionText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "900",
  },
} satisfies Record<string, ViewStyle | TextStyle | ImageStyle>;
