import type { ImageStyle, TextStyle, ViewStyle } from "react-native";

export const productTreeStyles = {
  productListContent: {
    padding: 12,
    gap: 9,
  },
  productRootHeader: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  productRootTitle: {
    color: "#f4f8ff",
    fontSize: 15,
    fontWeight: "900",
  },
  productRootMeta: {
    color: "#8f9caf",
    fontSize: 11,
    fontWeight: "800",
  },
  productContextPanel: {
    borderWidth: 1,
    borderColor: "#2f3948",
    borderRadius: 8,
    backgroundColor: "#111820",
    padding: 11,
    gap: 7,
  },
  productBreadcrumbRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 28,
  },
  productBackButton: {
    minHeight: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#36465a",
    backgroundColor: "#172231",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  productBackText: {
    color: "#eaf2fb",
    fontSize: 12,
    fontWeight: "900",
  },
  productPathLine: {
    flex: 1,
    color: "#8895a8",
    fontSize: 12,
    fontWeight: "800",
  },
  productContextTitle: {
    color: "#f4f8ff",
    fontSize: 19,
    lineHeight: 23,
    fontWeight: "900",
  },
  productContextSummary: {
    color: "#a4afbf",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  productNodeRow: {
    borderWidth: 1,
    borderColor: "#2f3948",
    borderRadius: 8,
    backgroundColor: "#111820",
    padding: 12,
  },
  productNodeMain: {
    gap: 8,
  },
  productNodeTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  productNodeTitle: {
    flex: 1,
    color: "#f4f8ff",
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "900",
  },
  productNodeChevron: {
    color: "#92cff5",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
    marginTop: 3,
  },
  productNodePath: {
    color: "#748296",
    fontSize: 11,
    fontWeight: "800",
  },
  productNodeSummary: {
    color: "#a6b0c0",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  productNodeMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 7,
  },
  productKindBadge: {
    overflow: "hidden",
    borderRadius: 8,
    backgroundColor: "#203149",
    color: "#b9d4f2",
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: "900",
  },
  productNodeMeta: {
    color: "#8e9bad",
    fontSize: 11,
    fontWeight: "800",
  },
  productSearchScreen: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  productSearchInput: {
    marginHorizontal: 14,
    marginTop: 14,
    marginBottom: 4,
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#354253",
    backgroundColor: "#121820",
    color: "#f4f8ff",
    paddingHorizontal: 12,
    fontSize: 14,
    fontWeight: "700",
  },
  productSearchCount: {
    color: "#8f9caf",
    fontSize: 12,
    fontWeight: "900",
    marginBottom: 2,
  },
  productOverviewScreen: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  productOverviewCard: {
    borderWidth: 1,
    borderColor: "#2f3948",
    borderRadius: 8,
    backgroundColor: "#111820",
    padding: 12,
    gap: 8,
  },
  productOverviewTitle: {
    color: "#f4f8ff",
    fontSize: 16,
    fontWeight: "900",
  },
  productOverviewText: {
    color: "#a6b0c0",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  productOverviewGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  productOverviewMetric: {
    width: "48%",
    minHeight: 72,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2f3948",
    backgroundColor: "#111820",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  productTagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
} satisfies Record<string, ViewStyle | TextStyle | ImageStyle>;
