import type { ImageStyle, TextStyle, ViewStyle } from "react-native";

export const productShellStyles = {
  productScreen: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  productHeader: {
    borderBottomWidth: 1,
    borderBottomColor: "#242b35",
    backgroundColor: "#10151d",
    paddingHorizontal: 14,
    paddingTop: 7,
    paddingBottom: 8,
    gap: 6,
  },
  productHeaderTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  productHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  productEyebrow: {
    color: "#8390a3",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  productHeaderTitle: {
    color: "#f4f8ff",
    fontSize: 19,
    fontWeight: "900",
  },
  productHeaderSummary: {
    color: "#9da8b8",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
  },
  productChangeButton: {
    minHeight: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#3c82ad",
    backgroundColor: "#102a3d",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 11,
  },
  productChangeText: {
    color: "#d4efff",
    fontSize: 12,
    fontWeight: "900",
  },
  productRefreshButton: {
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#36465a",
    backgroundColor: "#1a2532",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  productRefreshText: {
    color: "#eaf2fb",
    fontSize: 12,
    fontWeight: "900",
  },
  productPickerRow: {
    gap: 7,
    paddingRight: 6,
  },
  productPickerChip: {
    maxWidth: 220,
    minHeight: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2d3847",
    backgroundColor: "#121820",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  productPickerChipActive: {
    borderColor: "#4aa3d8",
    backgroundColor: "#123149",
  },
  productPickerText: {
    color: "#9ca8ba",
    fontSize: 12,
    fontWeight: "900",
  },
  productPickerTextActive: {
    color: "#eef8ff",
  },
  productStatsRow: {
    flexDirection: "row",
    gap: 8,
  },
  productStat: {
    flex: 1,
    minHeight: 58,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2f3948",
    backgroundColor: "#121820",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  productStatValue: {
    color: "#f4f8ff",
    fontSize: 18,
    fontWeight: "900",
  },
  productStatLabel: {
    color: "#8f9caf",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
    marginTop: 3,
  },
  productModeRow: {
    flexDirection: "row",
    gap: 6,
    minHeight: 32,
  },
  productModeButton: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2f3948",
    backgroundColor: "#121820",
    alignItems: "center",
    justifyContent: "center",
  },
  productModeButtonActive: {
    borderColor: "#2f8fc8",
    backgroundColor: "#123149",
  },
  productModeText: {
    color: "#9ca8ba",
    fontSize: 12,
    fontWeight: "900",
  },
  productModeTextActive: {
    color: "#eef8ff",
  },
} satisfies Record<string, ViewStyle | TextStyle | ImageStyle>;
