import type { ImageStyle, TextStyle, ViewStyle } from "react-native";

export const shellStyles = {
  safeArea: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  shell: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  header: {
    borderBottomWidth: 1,
    borderBottomColor: "#242b35",
    paddingHorizontal: 14,
    paddingTop: 6,
    paddingBottom: 7,
    gap: 6,
    backgroundColor: "#10151d",
  },
  content: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  nativeVoiceBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#2f3642",
    backgroundColor: "#151922",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  voiceButton: {
    minWidth: 86,
    minHeight: 42,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0e639c",
    paddingHorizontal: 14,
  },
  voiceButtonRecording: {
    backgroundColor: "#b33939",
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  voiceButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
  },
  voiceStatusBlock: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  voiceStatus: {
    color: "#f4f8ff",
    fontSize: 13,
    fontWeight: "800",
  },
  voiceTranscript: {
    color: "#9aa8bd",
    fontSize: 12,
  },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  titleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  title: {
    color: "#f4f8ff",
    fontSize: 21,
    fontWeight: "900",
  },
  url: {
    color: "#9aa8bd",
    fontSize: 12,
    marginTop: 2,
  },
  connectionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  connectionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  connectionDotReady: {
    backgroundColor: "#49c27c",
  },
  connectionDotMissing: {
    backgroundColor: "#d99b35",
  },
  connectionText: {
    color: "#96a4b8",
    fontSize: 11,
    fontWeight: "800",
  },
  setupPanel: {
    gap: 8,
  },
  setupCaption: {
    color: "#8390a3",
    fontSize: 11,
    fontWeight: "700",
  },
  settingsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    borderWidth: 1,
    borderColor: "#2f3948",
    borderRadius: 8,
    backgroundColor: "#121820",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  settingsCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  settingsLabel: {
    color: "#f4f8ff",
    fontSize: 13,
    fontWeight: "900",
  },
  settingsDescription: {
    color: "#95a3b7",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
  },
  input: {
    backgroundColor: "#12161c",
    borderColor: "#364152",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#f4f8ff",
  },
  flexInput: {
    flex: 1,
    minWidth: 0,
  },
  optionalGrid: {
    flexDirection: "row",
    gap: 8,
  },
  actionRow: {
    flexDirection: "row",
    gap: 8,
  },
  button: {
    backgroundColor: "#223040",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  headerButton: {
    minHeight: 36,
    borderRadius: 8,
    justifyContent: "center",
    backgroundColor: "#1d2a38",
    paddingHorizontal: 12,
  },
  buttonText: {
    color: "#edf3ff",
    fontWeight: "900",
    fontSize: 13,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: "#0e639c",
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 15,
  },
  webView: {
    flex: 1,
    backgroundColor: "#101317",
  },
  bottomTabs: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: "#242b35",
    backgroundColor: "#10151d",
    paddingHorizontal: 6,
    paddingTop: 8,
    paddingBottom: 8,
    gap: 4,
  },
  tabItem: {
    flex: 1,
    minHeight: 50,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  tabItemActive: {
    backgroundColor: "#1d2a38",
  },
  tabIndicator: {
    width: 20,
    height: 3,
    borderRadius: 2,
    backgroundColor: "transparent",
  },
  tabIndicatorActive: {
    backgroundColor: "#69c7ff",
  },
  tabText: {
    color: "#94a1b4",
    fontSize: 11,
    fontWeight: "900",
  },
  tabTextActive: {
    color: "#f4f8ff",
  },
  loading: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#101317",
  },
  errorPanel: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 18,
    gap: 10,
    backgroundColor: "#111317",
  },
  errorTitle: {
    color: "#f4f8ff",
    fontSize: 16,
    fontWeight: "700",
  },
  errorText: {
    color: "#9aa8bd",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
  },
} satisfies Record<string, ViewStyle | TextStyle | ImageStyle>;
