import type { ImageStyle, TextStyle, ViewStyle } from "react-native";

export const voiceStyles = {
  voiceScreen: {
    flex: 1,
    backgroundColor: "#0d1015",
  },
  voiceTopBand: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
  },
  voiceTopCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  voiceTitle: {
    color: "#f4f8ff",
    fontSize: 22,
    fontWeight: "900",
  },
  voiceSubtitle: {
    color: "#9ba8ba",
    fontSize: 12,
    fontWeight: "700",
  },
  runtimeChip: {
    maxWidth: 190,
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2f8fc8",
    backgroundColor: "#10293a",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  runtimeChipText: {
    color: "#b9e4ff",
    fontSize: 11,
    fontWeight: "900",
  },
  voiceModeRow: {
    flexDirection: "row",
    gap: 7,
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  voiceModeButton: {
    flex: 1,
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2f3948",
    backgroundColor: "#121820",
    alignItems: "center",
    justifyContent: "center",
  },
  voiceModeButtonActive: {
    borderColor: "#2f8fc8",
    backgroundColor: "#123149",
  },
  voiceModeText: {
    color: "#9ca8ba",
    fontSize: 12,
    fontWeight: "900",
  },
  voiceModeTextActive: {
    color: "#eef8ff",
  },
  voiceConversation: {
    flex: 1,
  },
  voiceConversationContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 12,
    gap: 12,
  },
  voiceBubble: {
    maxWidth: "86%",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  voiceBubbleAssistant: {
    alignSelf: "flex-start",
    backgroundColor: "#202733",
    borderTopLeftRadius: 3,
  },
  voiceBubbleUser: {
    alignSelf: "flex-end",
    backgroundColor: "#0e639c",
    borderTopRightRadius: 3,
  },
  voiceBubbleText: {
    fontSize: 15,
    lineHeight: 22,
  },
  voiceBubbleTextAssistant: {
    color: "#eef4fb",
  },
  voiceBubbleTextUser: {
    color: "#ffffff",
  },
  plannerTraceList: {
    gap: 7,
    marginTop: 10,
  },
  plannerTraceCard: {
    borderWidth: 1,
    borderColor: "#354457",
    borderRadius: 8,
    backgroundColor: "#151c26",
    padding: 9,
    gap: 5,
  },
  plannerTraceHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  plannerTraceTitle: {
    flex: 1,
    color: "#d9eaff",
    fontSize: 11,
    fontWeight: "900",
  },
  plannerTraceStatus: {
    color: "#76dbac",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  plannerTraceStatusError: {
    color: "#ff9c9c",
  },
  plannerTraceMeta: {
    color: "#9aa8bd",
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "700",
  },
  voiceComposerPanel: {
    marginHorizontal: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#2f3948",
    borderRadius: 24,
    backgroundColor: "#111820",
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 10,
    gap: 8,
  },
  voiceComposerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingHorizontal: 4,
  },
  voiceComposerLabel: {
    flex: 1,
    color: "#e8eef7",
    fontSize: 13,
    fontWeight: "900",
  },
  voiceComposerStatus: {
    maxWidth: 178,
    color: "#8fa0b6",
    fontSize: 11,
    fontWeight: "800",
  },
  voiceComposerInput: {
    minHeight: 50,
    maxHeight: 112,
    color: "#f4f8ff",
    fontSize: 16,
    lineHeight: 22,
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  voiceComposerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 42,
  },
  voiceClearButton: {
    minWidth: 68,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: "#344052",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#151c26",
    paddingHorizontal: 12,
  },
  voiceClearButtonText: {
    color: "#c5d0df",
    fontSize: 13,
    fontWeight: "900",
  },
  voiceComposerSpacer: {
    flex: 1,
  },
  voiceMicButton: {
    minWidth: 58,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1a2330",
    borderWidth: 1,
    borderColor: "#39485c",
  },
  voiceMicButtonRecording: {
    backgroundColor: "#b33939",
    borderColor: "#d65f5f",
  },
  voiceMicButtonText: {
    color: "#eaf2fb",
    fontSize: 13,
    fontWeight: "900",
  },
  voiceSendButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  voiceSendButtonText: {
    color: "#0d1015",
    fontSize: 25,
    lineHeight: 28,
    fontWeight: "900",
  },
  voiceControlHint: {
    paddingHorizontal: 4,
    color: "#9ba8ba",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
  },
} satisfies Record<string, ViewStyle | TextStyle | ImageStyle>;
