import { useQueryClient } from "@tanstack/react-query";
import { useLocation, useNavigate } from "react-router-dom";
import { revealInFinder } from "../../../lib/tauri";
import { useWorkspaceStore } from "../../../state/workspaceStore";
import { usePlannerAssistantSpeech } from "./usePlannerAssistantSpeech";
import { usePlannerComposerSubmit } from "./usePlannerComposerSubmit";
import { usePlannerDesignPacketExport } from "./usePlannerDesignPacketExport";
import { usePlannerDraftActions } from "./usePlannerDraftActions";
import { usePlannerDraftEditorState } from "./usePlannerDraftEditorState";
import { usePlannerPageLifecycle } from "./usePlannerPageLifecycle";
import { usePlannerPageViewModel } from "./usePlannerPageViewModel";
import { usePlannerPageCoreState } from "./usePlannerPageCoreState";
import { usePlannerMutationResultHandler } from "./usePlannerMutationResultHandler";
import { usePlannerPendingPlanActions } from "./usePlannerPendingPlanActions";
import { usePlannerRepositoryAnalysis } from "./usePlannerRepositoryAnalysis";
import { usePlannerSpeechSettingsState } from "./usePlannerSpeechSettingsState";
import { usePlannerTurnMutations } from "./usePlannerTurnMutations";
import { usePlannerVoiceCapture } from "./usePlannerVoiceCapture";
import { usePlannerVoiceSubmission } from "./usePlannerVoiceSubmission";
import { usePlannerVoiceTranscriptHandler } from "./usePlannerVoiceTranscriptHandler";
import { usePlannerWindowWidth } from "./usePlannerWindowWidth";

export function usePlannerPageController() {
  const queryClient = useQueryClient();
  const location = useLocation();
  const navigate = useNavigate();
  const { activeProductId, activeProductAreaId, activeCapabilityId, activeWorkItemId, setActiveProduct } = useWorkspaceStore();
  const {
    activePlannerProductRef,
    composerRef,
    consumedRoutePromptRef,
    draft,
    draftTreeNodes,
    expandedDraftNodeIds,
    latestTraceEvents,
    messages,
    modelName,
    pendingPlan,
    plannerBusyRef,
    plannerView,
    providerId,
    selectedDraftNodeId,
    sessionId,
    setDraft,
    setDraftTreeNodes,
    setExpandedDraftNodeIds,
    setLatestTraceEvents,
    setMessages,
    setModelName,
    setPendingPlan,
    setPlannerView,
    setProviderId,
    setSelectedDraftNodeId,
    setSessionId,
    setShowCompactTools,
    showCompactTools,
    speechModelSelectionRef,
    submitVoiceTranscriptRef,
    transcriptRef,
  } = usePlannerPageCoreState();
  const {
    voiceEnabled,
    autoSpeak,
    speechProviderSetting,
    speechModelSetting,
    speechLocaleSetting,
    speechNativeVoiceSetting,
    reviewVoiceBeforeSend,
  } = usePlannerSpeechSettingsState();
  const { speakAssistantReply } = usePlannerAssistantSpeech({
    speechLocaleSetting,
    speechNativeVoiceSetting,
  });
  const windowWidth = usePlannerWindowWidth();
  const {
    isListening,
    isTranscribing,
    isVoiceSubmitting,
    setIsVoiceSubmitting,
    pendingVoiceTranscript,
    setPendingVoiceTranscript,
    editableVoiceTranscript,
    setEditableVoiceTranscript,
    voiceActivity,
    setVoiceActivity,
    voiceElapsedMs,
    speechError,
    setSpeechError,
    isVoiceCaptureBusy,
    clearPendingVoiceReview,
    submitPendingVoiceTranscript,
    retryVoiceCapture,
    toggleListening,
  } = usePlannerVoiceCapture({
    voiceEnabled,
    reviewVoiceBeforeSend,
    getSpeechModelSelection: () => speechModelSelectionRef.current,
    speechLocaleSetting,
    isPlannerBusy: () => plannerBusyRef.current,
    onSubmitVoiceTranscript: (transcript) => submitVoiceTranscriptRef.current(transcript),
  });

  const {
    products,
    providers,
    models,
    repositories,
    selectedProductId,
    selectedProduct,
    workItems,
    plannerWorkItemsHasMore,
    productTrees,
    hasTreeData,
    isFocusedWorkspaceView,
    isCompactScreen,
    selectedDraftNode,
    selectedDraftNodePath,
    expandedDraftNodeIdSet,
    latestDraftPlan,
    selectedDraftNodePrompts,
    allowedDraftChildTypes,
    draftValidation,
    selectedNodeRecentActions,
    latestAssistantMessage,
    plannerStatusSummary,
    composerScopeChips,
    modelOptions,
    plannerModelPickerOptions,
    plannerModelPickerValue,
    speechModelSelection,
    context,
    activeProductName,
  } = usePlannerPageViewModel({
    activeProductId,
    activeProductAreaId,
    activeCapabilityId,
    activeWorkItemId,
    selectedDraftNodeId,
    expandedDraftNodeIds,
    draftTreeNodes,
    messages,
    pendingPlan,
    voiceActivity,
    pendingVoiceTranscript,
    reviewVoiceBeforeSend,
    plannerView,
    windowWidth,
    providerId,
    modelName,
    speechProviderSetting,
    speechModelSetting,
  });
  speechModelSelectionRef.current = speechModelSelection;
  const {
    renameDraftName,
    setRenameDraftName,
    draftChildType,
    setDraftChildType,
    draftChildName,
    setDraftChildName,
    draftChildSummary,
    setDraftChildSummary,
    draftEditError,
    setDraftEditError,
    draftEditMessage,
    setDraftEditMessage,
  } = usePlannerDraftEditorState({
    selectedDraftNode,
    selectedDraftNodeId,
    allowedDraftChildTypes,
  });
  const {
    designPacketPath,
    designPacketError,
    isExportingDesignPacket,
    exportDesignReviewPacket,
  } = usePlannerDesignPacketExport({
    queryClient,
    selectedProductId,
    productTrees,
    activeProductName,
    products,
    workItems,
    plannerWorkItemsHasMore,
    draftTreeNodes,
    latestDraftPlan,
    draftValidation,
    selectedDraftNode,
    latestAssistantMessage,
    onAppendMessage: setMessages,
  });

  usePlannerPageLifecycle({
    selectedProductId,
    selectedProduct,
    sessionId,
    setSessionId,
    draftTreeNodes,
    setDraftTreeNodes,
    selectedDraftNodeId,
    setSelectedDraftNodeId,
    setExpandedDraftNodeIds,
    setLatestTraceEvents,
    pendingPlan,
    setPendingPlan,
    plannerView,
    setPlannerView,
    setMessages,
    providerId,
    setProviderId,
    providers,
    modelName,
    setModelName,
    modelOptions,
    transcriptRef,
    messages,
    location,
    navigate,
    setDraft,
    composerRef,
    consumedRoutePromptRef,
    activePlannerProductRef,
    isCompactScreen,
    setShowCompactTools,
  });

  const handlePlannerMutationSuccess = usePlannerMutationResultHandler({
    queryClient,
    selectedProductId,
    draftTreeNodes,
    setPendingVoiceTranscript,
    setEditableVoiceTranscript,
    setVoiceActivity,
    setIsVoiceSubmitting,
    setLatestTraceEvents,
    setMessages,
    setDraftTreeNodes,
    setPlannerView,
    setSelectedDraftNodeId,
    setExpandedDraftNodeIds,
    setPendingPlan,
    autoSpeak,
    speakAssistantReply,
  });

  const {
    processMutation,
    draftEditMutation,
  } = usePlannerTurnMutations({
    selectedProductId,
    sessionId,
    setSessionId,
    providerId,
    modelName,
    selectedDraftNodeId,
    setPendingVoiceTranscript,
    setEditableVoiceTranscript,
    setVoiceActivity,
    setIsVoiceSubmitting,
    setLatestTraceEvents,
    setMessages,
    setDraftEditError,
    setDraftEditMessage,
    onPlannerMutationSuccess: handlePlannerMutationSuccess,
  });

  const {
    showRepoModal,
    setShowRepoModal,
    selectedRepositoryId,
    setSelectedRepositoryId,
    repositoryPathDraft,
    setRepositoryPathDraft,
    repoAnalysisMessage,
    repoAnalysisError,
    isRepositoryAnalysisPending,
    browseRepositoryPathForPlanner,
    registerRepositoryForPlanner,
    analyzeSelectedRepository,
    isPlannerBusy,
  } = usePlannerRepositoryAnalysis({
    draftEditMutation,
    handlePlannerMutationSuccess,
    isVoiceCaptureBusy,
    plannerBusyRef,
    processMutation,
    queryClient,
    repositories,
    sessionId,
    selectedDraftNodeId,
    selectedProductId,
  });

  const { send } = usePlannerComposerSubmit({
    draft,
    isPlannerBusy,
    processMutation,
    selectedProductId,
    setDraft,
    setMessages,
  });

  const {
    confirmPendingPlan,
    dismissPendingPlan,
  } = usePlannerPendingPlanActions({
    queryClient,
    pendingPlan,
    setPendingPlan,
    draftTreeNodes,
    setDraftTreeNodes,
    sessionId,
    isPlannerBusy,
    selectedProductId,
    setLatestTraceEvents,
    setMessages,
    setSelectedDraftNodeId,
    setPlannerView,
  });

  const {
    toggleDraftNodeExpanded,
    expandAllDraftNodes,
    collapseAllDraftNodes,
    applyPromptSuggestion,
    renameSelectedDraftNode,
    addChildToSelectedDraftNode,
    deleteSelectedDraftNode,
  } = usePlannerDraftActions({
    draftTreeNodes,
    setExpandedDraftNodeIds,
    setDraft,
    composerRef,
    selectedDraftNode,
    renameDraftName,
    draftChildType,
    draftChildName,
    setDraftChildName,
    draftChildSummary,
    setDraftChildSummary,
    allowedDraftChildTypes,
    isPlannerBusy,
    setDraftEditError,
    setDraftEditMessage,
    draftEditMutation,
  });

  const handleVoiceTranscript = usePlannerVoiceTranscriptHandler({
    autoSpeak,
    draftTreeNodes,
    latestTraceEvents,
    selectedProductId,
    sessionId,
    setSessionId,
    providerId,
    modelName,
    selectedDraftNodeId,
    selectedDraftNodePath,
    setPendingVoiceTranscript,
    setEditableVoiceTranscript,
    setVoiceActivity,
    setMessages,
    setPlannerView,
    setExpandedDraftNodeIds,
    expandAllDraftNodes,
    collapseAllDraftNodes,
    onPlannerMutationSuccess: handlePlannerMutationSuccess,
    speakAssistantReply,
  });
  usePlannerVoiceSubmission({
    clearPendingVoiceReview,
    composerRef,
    handleVoiceTranscript,
    isPlannerBusy,
    selectedProductId,
    setDraft,
    setIsVoiceSubmitting,
    setPendingVoiceTranscript,
    setSpeechError,
    setVoiceActivity,
    submitVoiceTranscriptRef,
  });

  return {
    allowedDraftChildTypes,
    analyzeSelectedRepository,
    browseRepositoryPathForPlanner,
    clearPendingVoiceReview,
    collapseAllDraftNodes,
    composerRef,
    composerScopeChips,
    confirmPendingPlan,
    context,
    deleteSelectedDraftNode,
    designPacketError,
    designPacketPath,
    dismissPendingPlan,
    draft,
    draftChildName,
    draftChildSummary,
    draftChildType,
    draftEditError,
    draftEditMessage,
    draftTreeNodes,
    draftValidation,
    editableVoiceTranscript,
    expandedDraftNodeIdSet,
    expandAllDraftNodes,
    exportDesignReviewPacket,
    hasTreeData,
    isCompactScreen,
    isExportingDesignPacket,
    isFocusedWorkspaceView,
    isListening,
    isPlannerBusy,
    isVoiceSubmitting,
    isTranscribing,
    latestDraftPlan,
    latestTraceEvents,
    messages,
    modelName,
    navigate,
    pendingPlan,
    pendingVoiceTranscript,
    plannerModelPickerOptions,
    plannerModelPickerValue,
    plannerStatusSummary,
    plannerView,
    plannerWorkItemsHasMore,
    products,
    providerId,
    providers,
    registerRepositoryForPlanner,
    repoAnalysisError,
    repoAnalysisMessage,
    repositories,
    repositoryPathDraft,
    retryVoiceCapture,
    reviewVoiceBeforeSend,
    revealInFinder,
    selectedDraftNode,
    selectedDraftNodeId,
    selectedDraftNodePath,
    selectedDraftNodePrompts,
    selectedNodeRecentActions,
    selectedProductId,
    selectedRepositoryId,
    send,
    setActiveProduct,
    setDraftChildName,
    setDraftChildSummary,
    setDraftChildType,
    setEditableVoiceTranscript,
    setModelName,
    setPlannerView,
    setProviderId,
    setRenameDraftName,
    setRepositoryPathDraft,
    setSelectedDraftNodeId,
    setSelectedRepositoryId,
    setShowCompactTools,
    setDraft,
    showCompactTools,
    showRepoModal,
    setShowRepoModal,
    submitPendingVoiceTranscript,
    toggleListening,
    toggleDraftNodeExpanded,
    transcriptRef,
    voiceElapsedMs,
    voiceEnabled,
    voiceActivity,
    applyPromptSuggestion,
    renameDraftName,
    renameSelectedDraftNode,
    addChildToSelectedDraftNode,
  };
}

export type PlannerPageController = ReturnType<typeof usePlannerPageController>;
