import React, { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { listProducts, listRepositories } from "../../../lib/tauri";
import { listCiTargetBindings, saveCiTargetBinding } from "../../../lib/tauri/ci";

const field: React.CSSProperties = { padding: "8px", border: "1px solid #b8c4d7", borderRadius: 6, background: "white", color: "#263249" };
export function CiBindingPanel({ targets }: { targets: Array<{ id: string; profile: string }> }) {
  const client = useQueryClient(); const products = useQuery({ queryKey: ["products"], queryFn: listProducts }); const repositories = useQuery({ queryKey: ["repositories"], queryFn: listRepositories }); const bindings = useQuery({ queryKey: ["ci-target-bindings"], queryFn: listCiTargetBindings });
  const [productId, setProductId] = useState(""); const [repositoryId, setRepositoryId] = useState(""); const [targetId, setTargetId] = useState("");
  const save = useMutation({ mutationFn: () => saveCiTargetBinding({ product_id: productId, repository_id: repositoryId, target_id: targetId, auto_preview: true }), onSuccess: () => void client.invalidateQueries({ queryKey: ["ci-target-bindings"] }) });
  return <section style={{ background: "#fff", border: "1px solid #d9dfeb", borderRadius: 12, padding: 16, marginBottom: 16 }}><strong>Automatic Preview bindings</strong><p style={{ color: "#657085", fontSize: 13 }}>Map a product and repository to an approved Preview target. Successful coding commits will be queued automatically.</p><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><select aria-label="Product" style={field} value={productId} onChange={(e) => setProductId(e.target.value)}><option value="">Select product</option>{(products.data ?? []).map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select aria-label="Repository" style={field} value={repositoryId} onChange={(e) => setRepositoryId(e.target.value)}><option value="">Select repository</option>{(repositories.data ?? []).map((r) => <option key={r.id} value={r.id}>{r.name}</option>)}</select><select aria-label="Preview target" style={field} value={targetId} onChange={(e) => setTargetId(e.target.value)}><option value="">Select Preview target</option>{targets.filter((t) => t.id.endsWith("-preview")).map((t) => <option key={t.id} value={t.id}>{t.id}</option>)}</select><button disabled={!productId || !repositoryId || !targetId || save.isPending} onClick={() => save.mutate()} style={{ ...field, background: "#2864dc", color: "white", border: 0, fontWeight: 650 }}>Enable automation</button></div><div style={{ marginTop: 12, display: "grid", gap: 6 }}>{(bindings.data ?? []).map((b) => <div key={b.id} style={{ fontSize: 12, color: "#485974" }}>{b.product_id.slice(0, 8)} · {b.repository_id.slice(0, 8)} → <strong>{b.target_id}</strong> · automatic</div>)}</div>{save.error && <div style={{ color: "#c23636", marginTop: 8 }}>{String(save.error)}</div>}</section>;
}
