import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  layout: { display: "block" },
  article: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 10 },
  hero: {
    borderRadius: 8,
    border: "1px solid #d8dee8",
    background: "#ffffff",
    padding: 14,
  },
  eyebrow: { fontSize: 11, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" as const, color: "#2563eb", marginBottom: 8 },
  heroTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, marginBottom: 8 },
  title: { fontSize: 24, fontWeight: 900, color: "#0f172a", margin: 0, lineHeight: 1.05 },
  subtitle: { fontSize: 12, color: "#475569", lineHeight: 1.4, margin: 0 },
  prose: { fontSize: 12, color: "#334155", lineHeight: 1.45, whiteSpace: "pre-wrap" as const },
  button: { padding: "6px 10px", fontSize: 12, fontWeight: 700, backgroundColor: "#f8fafc", color: "#1e3a8a", border: "1px solid #93c5fd", borderRadius: 8, cursor: "pointer", whiteSpace: "nowrap" as const },
  plannerButton: { padding: "6px 10px", fontSize: 12, fontWeight: 800, backgroundColor: "#2563eb", color: "#ffffff", border: "1px solid #1d4ed8", borderRadius: 8, cursor: "pointer", whiteSpace: "nowrap" as const },
  subtleButton: { padding: "6px 9px", fontSize: 12, fontWeight: 700, backgroundColor: "#eff6ff", color: "#1d4ed8", border: "1px solid #93c5fd", borderRadius: 8, cursor: "pointer", whiteSpace: "nowrap" as const },
  toggleButton: { padding: "7px 12px", fontSize: 12, fontWeight: 700, backgroundColor: "#eff6ff", color: "#1d4ed8", border: "1px solid #93c5fd", borderRadius: 8, cursor: "pointer", whiteSpace: "nowrap" as const },
  progressPanel: { marginTop: 10, borderRadius: 8, border: "1px solid #d8dee8", backgroundColor: "#f8fafc", padding: 8 },
  progressRow: { display: "flex", justifyContent: "space-between", gap: 16, fontSize: 12, color: "#475569" },
  progressTrack: { width: "100%", height: 8, borderRadius: 999, backgroundColor: "#e2e8f0", overflow: "hidden", marginTop: 8 },
  progressFill: { height: "100%", borderRadius: 999, background: "linear-gradient(90deg, #16a34a 0%, #22c55e 100%)" },
  metricGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))", gap: 8, marginTop: 10 },
  metricCard: { borderRadius: 8, padding: 8, backgroundColor: "#ffffff", border: "1px solid #d8dee8" },
  metricLabel: { fontSize: 10, fontWeight: 800, color: "#64748b", textTransform: "uppercase" as const, letterSpacing: "0.08em" },
  metricValue: { fontSize: 18, fontWeight: 900, color: "#0f172a", marginTop: 2 },
  summaryGrid: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 8 },
  summaryCard: { borderRadius: 8, border: "1px solid #d8dee8", backgroundColor: "#ffffff", padding: 10 },
  sectionTitle: { fontSize: 10, fontWeight: 800, letterSpacing: "0.1em", textTransform: "uppercase" as const, color: "#64748b", marginBottom: 8 },
  summaryHeading: { fontSize: 15, fontWeight: 800, color: "#111827", margin: "0 0 4px" },
  list: { margin: 0, paddingLeft: 18, color: "#334155", display: "flex", flexDirection: "column", gap: 8, lineHeight: 1.65 },
  chipRow: { display: "flex", gap: 8, flexWrap: "wrap" as const },
  chip: { fontSize: 11, padding: "4px 8px", borderRadius: 999, backgroundColor: "#eff6ff", color: "#1d4ed8" },
  section: { borderRadius: 8, border: "1px solid #d8dee8", backgroundColor: "#ffffff", padding: 12 },
  sectionHeader: { display: "flex", flexDirection: "column", gap: 4, marginBottom: 10 },
  sectionHeading: { fontSize: 18, fontWeight: 900, color: "#111827", margin: 0 },
  sectionSubtitle: { fontSize: 12, color: "#64748b", lineHeight: 1.45, margin: 0 },
  empty: { fontSize: 13, color: "#64748b", fontStyle: "italic" as const, lineHeight: 1.6 },
  detailsShell: { borderRadius: 8, border: "1px solid #d8dee8", backgroundColor: "#ffffff", overflow: "hidden" },
  summary: { padding: "9px 12px", display: "grid", gridTemplateColumns: "20px minmax(0, 1fr) minmax(280px, auto)", alignItems: "start", gap: 10, cursor: "pointer", textAlign: "left" as const },
  summaryToggle: { width: 20, lineHeight: "20px", color: "#0f172a", fontSize: 15, fontWeight: 900, textAlign: "center" as const, userSelect: "none" as const },
  summaryLeft: { minWidth: 0, width: "100%", textAlign: "left" as const },
  summaryRight: { display: "flex", flexDirection: "column", gap: 6, alignItems: "flex-end", minWidth: 0 },
  summaryPillRow: { display: "flex", gap: 6, flexWrap: "wrap" as const, justifyContent: "flex-end" as const },
  chapterLabel: { fontSize: 10, fontWeight: 800, color: "#2563eb", letterSpacing: "0.14em", textTransform: "uppercase" as const, marginBottom: 4 },
  chapterTitle: { fontSize: 18, fontWeight: 900, color: "#111827", margin: 0, lineHeight: 1.12 },
  chapterSubtitle: { fontSize: 12, color: "#475569", lineHeight: 1.35, marginTop: 4 },
  summaryPill: { display: "inline-flex", alignItems: "center", borderRadius: 999, padding: "4px 8px", fontSize: 11, fontWeight: 700, backgroundColor: "#f8fafc", border: "1px solid #cbd5e1", color: "#475569" },
  statePill: { display: "inline-flex", alignItems: "center", borderRadius: 999, padding: "4px 8px", fontSize: 11, fontWeight: 800, border: "1px solid currentColor", backgroundColor: "#f8fafc" },
  detailsBody: { padding: "0 12px 10px 42px", display: "flex", flexDirection: "column", gap: 8 },
  nodeActionRow: { display: "flex", justifyContent: "flex-end", gap: 6, flexWrap: "wrap" as const },
  noteGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 8 },
  noteCard: { borderRadius: 8, border: "1px solid #d8dee8", backgroundColor: "#f8fafc", padding: 10 },
  referenceList: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 10 },
  referenceCard: { borderRadius: 8, border: "1px solid #d8dee8", backgroundColor: "#ffffff", padding: 12 },
  referenceTitle: { fontSize: 13, fontWeight: 800, color: "#111827", margin: "4px 0 0" },
  referenceUri: { display: "block", marginTop: 8, fontSize: 12, color: "#2563eb", wordBreak: "break-word" as const },
  noteHeading: { fontSize: 10, fontWeight: 800, letterSpacing: "0.08em", textTransform: "uppercase" as const, color: "#64748b", marginBottom: 6 },
  noteText: { fontSize: 12, color: "#334155", lineHeight: 1.45, whiteSpace: "pre-wrap" as const },
  metaRow: { display: "flex", gap: 6, flexWrap: "wrap" as const },
  metaPill: { fontSize: 11, padding: "3px 7px", borderRadius: 999, backgroundColor: "#eff6ff", color: "#1d4ed8" },
  pathText: { fontSize: 11, color: "#64748b", lineHeight: 1.35, marginTop: 4 },
  nested: { marginLeft: 0, paddingLeft: 12, borderLeft: "2px solid #cbd5e1", display: "flex", flexDirection: "column", gap: 8 },
  workItemList: { display: "flex", flexDirection: "column", gap: 8 },
  workItemCard: { borderRadius: 8, border: "1px solid #d8dee8", padding: 8, cursor: "pointer", backgroundColor: "#ffffff" },
  workItemHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12 },
  workItemTitle: { fontSize: 13, fontWeight: 800, color: "#111827", margin: 0, lineHeight: 1.25 },
  workItemText: { fontSize: 12, color: "#475569", lineHeight: 1.4, marginTop: 5 },
  workItemChildren: { marginTop: 8, marginLeft: 8, paddingLeft: 10, borderLeft: "1px solid #d8dee8" },
};
