import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  page: { display: "flex", flexDirection: "column", gap: 12, height: "100%" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12 },
  title: { fontSize: 22, fontWeight: 800, color: "#ffffff", margin: 0 },
  subtitle: { fontSize: 12, color: "#8f96a3", marginTop: 4 },
  actions: { display: "flex", gap: 8, alignItems: "center" },
  btn: { padding: "7px 12px", fontSize: 12, backgroundColor: "#0e639c", color: "#fff", border: "none", borderRadius: 8, cursor: "pointer", fontWeight: 700 },
  filterBar: { display: "flex", gap: 8, flexWrap: "wrap", borderBottom: "1px solid #32353d", paddingBottom: 10 },
  filter: { padding: "7px 12px", fontSize: 12, fontWeight: 700, borderRadius: 8, border: "1px solid #3b4049", backgroundColor: "#2c3139", color: "#cfd6e4", cursor: "pointer" },
  filterActive: { padding: "7px 12px", fontSize: 12, fontWeight: 700, borderRadius: 8, border: "1px solid #0e639c", backgroundColor: "#173247", color: "#ffffff", cursor: "pointer" },
  body: { display: "grid", gridTemplateColumns: "minmax(300px, 0.85fr) minmax(360px, 0.95fr) minmax(420px, 1.2fr)", gap: 12, minHeight: 0, flex: 1 },
  listPanel: { border: "1px solid #32353d", borderRadius: 8, backgroundColor: "#212327", minHeight: 0, overflow: "hidden", display: "flex", flexDirection: "column" },
  panelHeader: { padding: 12, borderBottom: "1px solid #32353d", display: "flex", justifyContent: "space-between", gap: 8, alignItems: "center" },
  panelTitle: { color: "#f3f3f3", fontSize: 13, fontWeight: 800 },
  panelMeta: { color: "#8f96a3", fontSize: 11 },
  list: { overflow: "auto", padding: 10, display: "flex", flexDirection: "column", gap: 8 },
  row: { width: "100%", textAlign: "left", border: "1px solid #2d3139", borderRadius: 8, backgroundColor: "#1b1d22", color: "#d7deea", padding: 10, cursor: "pointer" },
  rowActive: { border: "1px solid #57b0e5", backgroundColor: "#172536" },
  rowTop: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10 },
  source: { fontSize: 13, fontWeight: 800, color: "#f3f3f3", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  status: { fontSize: 10, fontWeight: 800, color: "#4ec9b0", textTransform: "uppercase" },
  statusFailed: { color: "#ff9b9b" },
  small: { fontSize: 11, color: "#8f96a3", marginTop: 4, lineHeight: 1.4 },
  sessionSummary: { padding: 12, borderBottom: "1px solid #32353d" },
  sessionStats: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 8 },
  sessionStat: { border: "1px solid #32353d", borderRadius: 8, backgroundColor: "#1b1d22", padding: 10, minWidth: 0 },
  sessionStatValue: { color: "#f4f7fb", fontSize: 14, fontWeight: 800, overflowWrap: "anywhere" },
  sessionStatLabel: { color: "#8f96a3", fontSize: 10, fontWeight: 800, textTransform: "uppercase", marginTop: 4 },
  callsSubTitle: { color: "#f3f3f3", fontSize: 13, fontWeight: 800, margin: "6px 0 8px" },
  callList: { display: "flex", flexDirection: "column", gap: 8, marginBottom: 12 },
  compactCall: { width: "100%", textAlign: "left", border: "1px solid #303640", borderRadius: 8, backgroundColor: "#191c22", color: "#d7deea", padding: 10, cursor: "pointer" },
  compactCallActive: { border: "1px solid #57b0e5", backgroundColor: "#142437" },
  compactCallMeta: { display: "flex", gap: 8, flexWrap: "wrap", color: "#8f96a3", fontSize: 11, marginTop: 5 },
  detailPanel: { border: "1px solid #32353d", borderRadius: 8, backgroundColor: "#212327", minHeight: 0, overflow: "auto", padding: 14 },
  detailTitle: { fontSize: 18, fontWeight: 800, color: "#ffffff", marginBottom: 4 },
  detailSub: { fontSize: 12, color: "#8f96a3", marginBottom: 12 },
  detailGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  detailItem: { borderTop: "1px solid #32353d", paddingTop: 8, minWidth: 0 },
  label: { fontSize: 10, fontWeight: 800, textTransform: "uppercase", color: "#8f96a3", marginBottom: 4 },
  value: { fontSize: 12, color: "#e8edf7", overflowWrap: "anywhere", lineHeight: 1.45 },
  snapshotGrid: { display: "grid", gridTemplateColumns: "1fr", gap: 10, marginTop: 12 },
  snapshotBox: { border: "1px solid #32353d", borderRadius: 8, backgroundColor: "#171a1f", overflow: "hidden" },
  snapshotHeader: { padding: "8px 10px", borderBottom: "1px solid #32353d", display: "flex", justifyContent: "space-between", gap: 8, alignItems: "center" },
  snapshotTitle: { fontSize: 11, fontWeight: 800, color: "#f3f3f3" },
  snapshotPath: { fontSize: 10, color: "#8f96a3", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  snapshotPre: { margin: 0, padding: 10, maxHeight: 260, overflow: "auto", color: "#d7deea", fontSize: 11, lineHeight: 1.45, whiteSpace: "pre-wrap", fontFamily: "JetBrains Mono, Menlo, Monaco, monospace" },
  errorBox: { marginTop: 12, border: "1px solid #5a2f35", backgroundColor: "#2b1d22", borderRadius: 8, padding: 10, color: "#ffb4b4", fontSize: 12, whiteSpace: "pre-wrap" },
  empty: { color: "#666", textAlign: "center", padding: 40, fontSize: 13 },
};
