import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  page: { display: "flex", flexDirection: "column", gap: 12, height: "100%", minHeight: 0 },
  header: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16 },
  title: { margin: 0, fontSize: 22, lineHeight: 1.15, color: "#111827", fontWeight: 800 },
  subtitle: { marginTop: 4, color: "#6b7280", fontSize: 13, lineHeight: 1.4 },
  tabBar: { display: "flex", gap: 8, padding: 4, border: "1px solid #d9e0ea", borderRadius: 10, backgroundColor: "#f8fafc", width: "fit-content" },
  tab: { border: "1px solid transparent", backgroundColor: "transparent", color: "#4b5563", borderRadius: 8, padding: "8px 13px", fontSize: 12, fontWeight: 800, cursor: "pointer" },
  tabActive: { border: "1px solid #2563eb", backgroundColor: "#eff6ff", color: "#1d4ed8", borderRadius: 8, padding: "8px 13px", fontSize: 12, fontWeight: 800, cursor: "pointer" },
  statGrid: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 10 },
  statCard: { border: "1px solid #d9e0ea", borderRadius: 10, backgroundColor: "#ffffff", padding: 12 },
  statLabel: { fontSize: 11, color: "#6b7280", textTransform: "uppercase", letterSpacing: "0.06em", fontWeight: 800 },
  statValue: { fontSize: 24, color: "#111827", fontWeight: 800, marginTop: 4 },
  summaryGrid: { display: "grid", gridTemplateColumns: "minmax(0, 1.35fr) minmax(320px, 0.65fr)", gap: 12, flex: 1, minHeight: 0 },
  manageGrid: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) 320px", gap: 12, flex: 1, minHeight: 0 },
  panel: { border: "1px solid #d9e0ea", borderRadius: 12, backgroundColor: "#ffffff", overflow: "hidden", minHeight: 0, display: "flex", flexDirection: "column" },
  panelHeader: { padding: "12px 14px", borderBottom: "1px solid #d9e0ea", display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10 },
  panelTitle: { fontSize: 12, color: "#6b7280", textTransform: "uppercase", letterSpacing: "0.08em", fontWeight: 800 },
  panelBody: { padding: 14, overflow: "auto", minHeight: 0, display: "flex", flexDirection: "column", gap: 12 },
  controlRow: { display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center" },
  button: { border: "1px solid #2563eb", backgroundColor: "#2563eb", color: "#ffffff", borderRadius: 8, padding: "8px 11px", fontSize: 12, fontWeight: 800, cursor: "pointer" },
  ghostButton: { border: "1px solid #cfd8e3", backgroundColor: "#f8fafc", color: "#111827", borderRadius: 8, padding: "7px 10px", fontSize: 12, fontWeight: 800, cursor: "pointer" },
  dangerButton: { border: "1px solid #dc2626", backgroundColor: "#ffffff", color: "#dc2626", borderRadius: 8, padding: "7px 10px", fontSize: 12, fontWeight: 800, cursor: "pointer" },
  section: { border: "1px solid #d9e0ea", borderRadius: 10, padding: 10, backgroundColor: "#f8fafc" },
  sectionTitle: { fontSize: 12, color: "#111827", fontWeight: 800, marginBottom: 8 },
  productGrid: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 10 },
  productCard: { border: "1px solid #d9e0ea", borderRadius: 10, backgroundColor: "#ffffff", padding: 12, display: "flex", flexDirection: "column", gap: 8 },
  productTitle: { fontSize: 14, color: "#111827", fontWeight: 800 },
  productText: { fontSize: 12, color: "#4b5563", lineHeight: 1.45 },
  badgeRow: { display: "flex", gap: 6, flexWrap: "wrap" },
  badge: { borderRadius: 999, backgroundColor: "#eef2ff", color: "#3730a3", padding: "3px 8px", fontSize: 11, fontWeight: 700 },
  badgeGreen: { borderRadius: 999, backgroundColor: "#dcfce7", color: "#166534", padding: "3px 8px", fontSize: 11, fontWeight: 700 },
  badgeMuted: { borderRadius: 999, backgroundColor: "#f3f4f6", color: "#4b5563", padding: "3px 8px", fontSize: 11, fontWeight: 700 },
  tree: { display: "flex", flexDirection: "column", gap: 8 },
  treeNode: { border: "1px solid #d9e0ea", borderRadius: 10, backgroundColor: "#ffffff", overflow: "hidden" },
  treeNodeActive: { border: "1px solid #2563eb", borderRadius: 10, backgroundColor: "#eff6ff", overflow: "hidden" },
  treeHeader: { display: "grid", gridTemplateColumns: "30px minmax(0, 1fr) auto", gap: 8, alignItems: "center", padding: "10px 11px" },
  toggle: { width: 24, height: 24, borderRadius: 7, border: "1px solid #cfd8e3", backgroundColor: "#f8fafc", color: "#111827", fontWeight: 800, cursor: "pointer" },
  togglePlaceholder: { width: 24, height: 24 },
  treeTitle: { color: "#111827", fontWeight: 800, fontSize: 13 },
  treeMeta: { color: "#6b7280", fontSize: 11, marginTop: 3, lineHeight: 1.35 },
  treeActions: { display: "flex", gap: 6, alignItems: "center" },
  treeChildren: { marginLeft: 24, padding: "0 0 10px 14px", borderLeft: "1px solid #d9e0ea", display: "flex", flexDirection: "column", gap: 8 },
  empty: { color: "#6b7280", fontSize: 13, padding: 16, textAlign: "center" },
  error: { color: "#dc2626", fontSize: 12 },
  label: { fontSize: 11, color: "#6b7280", fontWeight: 800, marginBottom: 4 },
  input: { width: "100%", boxSizing: "border-box", borderRadius: 8, border: "1px solid #cfd8e3", backgroundColor: "#ffffff", color: "#111827", padding: "8px 10px", fontSize: 12, marginBottom: 10 },
  textarea: { width: "100%", boxSizing: "border-box", borderRadius: 8, border: "1px solid #cfd8e3", backgroundColor: "#ffffff", color: "#111827", padding: "8px 10px", fontSize: 12, minHeight: 84, resize: "vertical", marginBottom: 10 },
  modalBackdrop: { position: "fixed", inset: 0, backgroundColor: "rgba(15, 23, 42, 0.42)", display: "flex", alignItems: "center", justifyContent: "center", padding: 24, zIndex: 50 },
  modal: { width: "min(620px, 100%)", maxHeight: "84vh", overflow: "hidden", borderRadius: 12, backgroundColor: "#ffffff", border: "1px solid #d9e0ea", boxShadow: "0 24px 60px rgba(15, 23, 42, 0.22)" },
  modalHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, padding: "13px 15px", borderBottom: "1px solid #d9e0ea" },
  modalTitle: { fontSize: 14, fontWeight: 800, color: "#111827" },
  modalBody: { padding: 15, maxHeight: "calc(84vh - 58px)", overflow: "auto" },
};
