import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  page: { display: "flex", flexDirection: "column", gap: 16, height: "100%", minHeight: 0 },
  headerRow: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12 },
  titleWrap: { display: "flex", flexDirection: "column", gap: 4 },
  title: { fontSize: 18, fontWeight: 700, color: "#111827", margin: 0 },
  subtitle: { fontSize: 13, color: "#6b7280", lineHeight: 1.4 },
  summaryRow: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 12 },
  statCard: { backgroundColor: "#ffffff", borderRadius: 12, border: "1px solid #d9e0ea", padding: 14, display: "flex", flexDirection: "column", gap: 6 },
  statLabel: { fontSize: 11, letterSpacing: "0.08em", textTransform: "uppercase", color: "#6b7280" },
  statValue: { fontSize: 24, fontWeight: 700, color: "#111827" },
  tabRow: { display: "flex", gap: 8, flexWrap: "wrap" },
  tab: { borderRadius: 10, border: "1px solid #d9e0ea", backgroundColor: "#f8fafc", color: "#374151", padding: "9px 14px", fontSize: 13, fontWeight: 700, cursor: "pointer" },
  tabActive: { backgroundColor: "#dbeafe", borderColor: "#2563eb", color: "#111827" },
  workspace: { display: "grid", gridTemplateColumns: "300px minmax(0, 1fr)", gap: 16, minHeight: 0, flex: 1 },
  rail: { backgroundColor: "#ffffff", borderRadius: 14, border: "1px solid #d9e0ea", padding: 14, display: "flex", flexDirection: "column", gap: 12, minHeight: 0 },
  detail: { backgroundColor: "#ffffff", borderRadius: 14, border: "1px solid #d9e0ea", padding: 16, display: "flex", flexDirection: "column", gap: 14, minHeight: 0, overflowY: "auto" as const },
  sectionTitle: { fontSize: 12, letterSpacing: "0.08em", textTransform: "uppercase", color: "#6b7280", fontWeight: 700 },
  list: { display: "flex", flexDirection: "column", gap: 8, overflowY: "auto", minHeight: 0 },
  listItem: { borderRadius: 12, border: "1px solid #d9e0ea", backgroundColor: "#ffffff", padding: 12, cursor: "pointer", display: "flex", flexDirection: "column", gap: 6 },
  listItemActive: { borderColor: "#2563eb", backgroundColor: "#eff6ff" },
  itemTitle: { fontSize: 14, fontWeight: 700, color: "#111827" },
  itemMeta: { fontSize: 12, color: "#6b7280", lineHeight: 1.35 },
  badgeRow: { display: "flex", gap: 8, flexWrap: "wrap" },
  badge: { fontSize: 11, borderRadius: 999, padding: "3px 8px", backgroundColor: "#dcfce7", color: "#166534" },
  badgeMuted: { fontSize: 11, borderRadius: 999, padding: "3px 8px", backgroundColor: "#eef2ff", color: "#3730a3" },
  toolbar: { display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center" },
  headerActions: { display: "flex", gap: 8, alignItems: "center", position: "relative" as const, zIndex: 5 },
  buttonPrimary: { borderRadius: 10, border: "1px solid #2563eb", backgroundColor: "#2563eb", color: "#ffffff", padding: "9px 14px", fontSize: 13, fontWeight: 700, cursor: "pointer" },
  buttonSecondary: { borderRadius: 10, border: "1px solid #cfd8e3", backgroundColor: "#f8fafc", color: "#111827", padding: "9px 14px", fontSize: 13, fontWeight: 700, cursor: "pointer" },
  buttonDanger: { borderRadius: 10, border: "1px solid #dc2626", backgroundColor: "#dc2626", color: "#ffffff", padding: "9px 14px", fontSize: 13, fontWeight: 700, cursor: "pointer" },
  formGrid: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 12 },
  fullWidth: { gridColumn: "1 / -1" },
  field: { display: "flex", flexDirection: "column", gap: 6 },
  label: { fontSize: 12, color: "#6b7280", fontWeight: 700 },
  input: { width: "100%", borderRadius: 10, border: "1px solid #cfd8e3", backgroundColor: "#ffffff", color: "#111827", padding: "10px 12px", fontSize: 13, boxSizing: "border-box" as const },
  textarea: { width: "100%", minHeight: 84, borderRadius: 10, border: "1px solid #cfd8e3", backgroundColor: "#ffffff", color: "#111827", padding: "10px 12px", fontSize: 13, resize: "vertical" as const, boxSizing: "border-box" as const },
  select: { width: "100%", borderRadius: 10, border: "1px solid #cfd8e3", backgroundColor: "#ffffff", color: "#111827", padding: "10px 12px", fontSize: 13, boxSizing: "border-box" as const },
  checkboxRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 13, color: "#374151" },
  infoCard: { borderRadius: 12, border: "1px solid #d9e0ea", backgroundColor: "#f8fafc", padding: 12, display: "flex", flexDirection: "column", gap: 6 },
  infoValue: { fontSize: 13, color: "#374151", lineHeight: 1.4 },
  split: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) minmax(280px, 360px)", gap: 16, minHeight: 0 },
  teamStatsRow: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 10 },
  teamStatChip: { borderRadius: 10, border: "1px solid #d9e0ea", backgroundColor: "#f8fafc", padding: 10, display: "flex", flexDirection: "column", gap: 4 },
  teamPanel: { borderRadius: 12, border: "1px solid #d9e0ea", backgroundColor: "#ffffff", padding: 14, display: "flex", flexDirection: "column", gap: 12 },
  teamPanelTitle: { fontSize: 12, letterSpacing: "0.08em", textTransform: "uppercase" as const, color: "#6b7280", fontWeight: 700, marginBottom: 2 },
  teamManagementGrid: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) minmax(320px, 420px)", gap: 16, minHeight: 0 },
  subList: { display: "flex", flexDirection: "column", gap: 8, maxHeight: 260, overflowY: "auto" as const },
  skillList: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 8 },
  skillPill: { borderRadius: 10, border: "1px solid #d9e0ea", backgroundColor: "#f8fafc", padding: "8px 10px", display: "flex", alignItems: "center", gap: 8 },
  error: { color: "#dc2626", fontSize: 12 },
  success: { color: "#047857", fontSize: 12 },
  empty: { color: "#6b7280", fontSize: 13, padding: "18px 0" },
  divider: { height: 1, backgroundColor: "#d9e0ea", margin: "4px 0" },
  treeTable: { display: "flex", flexDirection: "column", border: "1px solid #d9e0ea", borderRadius: 12, overflow: "hidden", backgroundColor: "#ffffff" },
  treeHeader: { display: "grid", gridTemplateColumns: "minmax(0, 1.4fr) 120px 130px 110px", gap: 10, padding: "10px 12px", borderBottom: "1px solid #d9e0ea", fontSize: 11, fontWeight: 700, letterSpacing: "0.06em", textTransform: "uppercase" as const, color: "#6b7280", backgroundColor: "#f8fafc" },
  treeRow: { display: "grid", gridTemplateColumns: "minmax(0, 1.4fr) 120px 130px 110px", gap: 10, padding: "10px 12px", borderBottom: "1px solid #edf2f7", alignItems: "center", cursor: "pointer", backgroundColor: "#ffffff" },
  treeRowActive: { backgroundColor: "#eff6ff" },
  treeNameCell: { display: "flex", alignItems: "center", gap: 8, minWidth: 0 },
  treeIndent: { width: 14, flexShrink: 0 },
  treeCaret: { width: 10, color: "#6b7280", fontSize: 11, flexShrink: 0 },
  treeName: { fontSize: 13, fontWeight: 700, color: "#111827", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" as const },
  treeSubName: { fontSize: 12, color: "#4b5563", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" as const },
  treeCell: { fontSize: 12, color: "#374151" },
  treeMetaBadge: { fontSize: 11, borderRadius: 999, padding: "3px 8px", backgroundColor: "#eef2ff", color: "#3730a3", display: "inline-block" },
  treeActions: { display: "flex", gap: 6, justifyContent: "flex-end" },
  treeActionBtn: { borderRadius: 7, border: "1px solid #cfd8e3", backgroundColor: "#f8fafc", color: "#111827", padding: "4px 7px", fontSize: 11, fontWeight: 700, cursor: "pointer" },
};
