import { useProductCatalogControls } from "./useProductCatalogControls";
import { useProductHierarchySelectionState } from "./useProductHierarchySelectionState";
import { useProductHierarchyMutations } from "./useProductHierarchyMutations";
import { useProductManagementSelection } from "./useProductManagementSelection";
import { useProductManagementWorkItemMutations } from "./useProductManagementWorkItemMutations";
import { useProductPageActions } from "./useProductPageActions";
import { useProductListPageState } from "./useProductListPageState";
import { useProductPageRefreshActions } from "./useProductPageRefreshActions";
import { useProductPageSync } from "./useProductPageSync";
import { useProductPageViewModel } from "./useProductPageViewModel";
import { useProductPageRuntimeContext } from "./useProductPageRuntimeContext";

export function useProductListPageController() {
  const { isProductDetailRoute, navigate, queryClient, ui, workspace } = useProductPageRuntimeContext();
  const {
    activeProductId,
    activeProductAreaId,
    activeCapabilityId,
    activeWorkItemId,
    setActiveProduct,
    setActiveProductArea,
    setActiveCapability,
    setActiveHierarchyNode,
    setActiveWorkItem,
  } = workspace;
  const {
    productDialogMode,
    productAreaDialogMode,
    capabilityDialogMode,
    closeProductDialog,
    openProductDialog,
    closeProductAreaDialog,
    openProductAreaDialog,
    closeCapabilityDialog,
    openCapabilityDialog,
    setProductWorkspaceTab,
    setActiveView,
  } = ui;

  const {
    productForm, setProductForm, productDraft, setProductDraft,
    productAreaForm, setProductAreaForm, productAreaDraft, setProductAreaDraft,
    capabilityForm, setCapabilityForm, capabilityDraft, setCapabilityDraft,
    productManagementTab, setProductManagementTab, formError, setFormError,
    productPageTab, setProductPageTab, dependencyDraft, setDependencyDraft,
    deleteProductCandidate, setDeleteProductCandidate, deleteConfirmName, setDeleteConfirmName,
    deleteConfirmArchive, setDeleteConfirmArchive, resetPlanCandidate, setResetPlanCandidate,
    resetPlanConfirmName, setResetPlanConfirmName, resetPlanConfirmTree, setResetPlanConfirmTree,
    resetPlanDeleteDelivery, setResetPlanDeleteDelivery, deleteHierarchyCandidate,
    setDeleteHierarchyCandidate, deleteHierarchyConfirmName, setDeleteHierarchyConfirmName,
    deleteHierarchyConfirmChecked, setDeleteHierarchyConfirmChecked,
    selectedManagementStoryId, setSelectedManagementStoryId,
    managementStoryPageIndex, setManagementStoryPageIndex,
    storyDialogMode, setStoryDialogMode, taskDialogMode, setTaskDialogMode,
    editingStory, setEditingStory, editingTask, setEditingTask,
    deleteWorkItemCandidate, setDeleteWorkItemCandidate,
    deleteWorkItemConfirmName, setDeleteWorkItemConfirmName,
    deleteWorkItemConfirmChecked, setDeleteWorkItemConfirmChecked,
    storyDraft, setStoryDraft, taskDraft, setTaskDraft,
    copiedEntityId, setCopiedEntityId,
    deleteConfirmationReady, resetPlanReady, deleteHierarchyReady,
    deleteManagementWorkItemReady,
  } = useProductListPageState({ isProductDetailRoute });

  const {
    productSearch,
    setProductSearch,
    productStatusFilter,
    setProductStatusFilter,
    productSourceFilter,
    setProductSourceFilter,
    productTagFilter,
    setProductTagFilter,
    productSort,
    setProductSort,
    showDefaultProductsInTable,
    setShowDefaultProductsInTable,
    showCustomProductsInTable,
    setShowCustomProductsInTable,
    catalogFilterMsg,
    catalogFilterError,
    statusProductId,
    setStatusProductId,
    statusDepth,
    setStatusDepth,
    statusGroupBy,
    setStatusGroupBy,
    updateDefaultProductVisibility,
  } = useProductCatalogControls({
    queryClient,
  });

  const {
    products,
    isLoading,
    productDependencies,
    selectedProductId,
    selectedProduct,
    tree,
    productTreeById,
    productTreeSummaryById,
    scopeSummaryIndex,
    allProductTags,
    includeDefaultProductsInCatalog,
    productTableRows,
    statusSummary,
    statusRows,
  } = useProductPageViewModel({
    activeProductId,
    productPageTab,
    productSearch,
    productStatusFilter,
    productSourceFilter,
    productTagFilter,
    productSort,
    showDefaultProductsInTable,
    showCustomProductsInTable,
    statusProductId,
    statusDepth,
    statusGroupBy,
  });

  const {
    productAreaOrderIds,
    capabilityOrderMap,
    selectedProductArea,
    selectedCapability,
    selectedCapabilityParentKind,
  } = useProductHierarchySelectionState({
    tree,
    activeProductAreaId,
    activeCapabilityId,
  });

  const {
    createProductMutation,
    updateProductMutation,
    createProductDependencyMutation,
    createProductAreaMutation,
    updateProductAreaMutation,
    createCapabilityMutation,
    updateCapabilityMutation,
    archiveMutation,
    resetProductPlanMutation,
    deleteHierarchyMutation,
    reorderProductAreasMutation,
    reorderCapabilitiesMutation,
    invalidateTasks,
  } = useProductHierarchyMutations({
    queryClient,
    selectedProductId,
    activeProductAreaId,
    activeCapabilityId,
    selectedProductArea,
    selectedCapability,
    productForm,
    setProductForm,
    productDraft,
    productAreaForm,
    setProductAreaForm,
    productAreaDraft,
    capabilityForm,
    setCapabilityForm,
    capabilityDraft,
    dependencyDraft,
    setDependencyDraft,
    statusProductId,
    setStatusProductId,
    closeProductDialog,
    closeProductAreaDialog,
    closeCapabilityDialog,
    setProductWorkspaceTab,
    setActiveProduct,
    setActiveProductArea,
    setActiveCapability,
    setDeleteProductCandidate,
    setDeleteConfirmName,
    setDeleteConfirmArchive,
    setResetPlanCandidate,
    setResetPlanConfirmName,
    setResetPlanConfirmTree,
    setResetPlanDeleteDelivery,
    setDeleteHierarchyCandidate,
    setDeleteHierarchyConfirmName,
    setDeleteHierarchyConfirmChecked,
    setFormError,
  });

  const {
    selectedCapabilityOptions,
    dependencyTargetCapabilityOptions,
    selectedProductDependencies,
    productNameById,
    capabilityLabelById,
    selectedCapabilityAllowedKindGroups,
    editableCapabilityNodeKindGroups,
    productAreaProductAreas,
    selectedProductAreaTree,
    selectedProductAreaNode,
    managementCapabilities,
    selectedManagementCapabilityTree,
    managementFeatures,
    allManagementFeatures,
    selectedManagementFeature,
    selectedManagementFeatureNode,
    managementFeatureWorkItemPage,
    featureStories,
    selectedManagementStory,
    selectedManagementStoryIdForTasks,
    selectedManagementTasks,
  } = useProductManagementSelection({
    tree,
    productTreeById,
    productDependencies,
    products,
    selectedProductId,
    selectedProductArea,
    selectedCapability,
    selectedCapabilityParentKind,
    dependencyDependsOnProductId: dependencyDraft.dependsOnProductId,
    productAreaOrderIds,
    capabilityOrderMap,
    activeProductAreaId,
    activeCapabilityId,
    activeWorkItemId,
    selectedManagementStoryId,
    managementStoryPageIndex,
    productPageTab,
    productManagementTab,
  });
  const {
    createManagementStoryMutation,
    updateManagementStoryMutation,
    createManagementTaskMutation,
    updateManagementTaskMutation,
    deleteManagementWorkItemMutation,
  } = useProductManagementWorkItemMutations({
    selectedProductId,
    selectedManagementFeatureNode,
    selectedManagementStory,
    setSelectedManagementStoryId,
    setActiveWorkItem,
    storyDraft,
    setStoryDraft,
    taskDraft,
    setTaskDraft,
    editingStory,
    setEditingStory,
    editingTask,
    setEditingTask,
    setStoryDialogMode,
    setTaskDialogMode,
    setDeleteWorkItemCandidate,
    setDeleteWorkItemConfirmName,
    setDeleteWorkItemConfirmChecked,
    setFormError,
    invalidateTasks,
  });
  useProductPageSync({
    isLoading,
    activeProductId,
    selectedProductId,
    products,
    setActiveProduct,
    statusProductId,
    setStatusProductId,
    setActiveWorkItem,
    activeProductAreaId,
    activeCapabilityId,
    selectedProduct,
    setProductForm,
    setProductDraft,
    productDialogMode,
    selectedProductArea,
    setProductAreaForm,
    setProductAreaDraft,
    productAreaDialogMode,
    selectedCapability,
    setCapabilityForm,
    setCapabilityDraft,
    capabilityDialogMode,
    selectedManagementFeatureNode,
    productManagementTab,
    setSelectedManagementStoryId,
    setManagementStoryPageIndex,
    setFormError,
  });
  const {
    activeProductPageRefreshLabel,
    activeProductPageRefreshDisabled,
    productManagementRefreshLabel,
    refreshActiveProductPageTab,
    refreshProductManagementTabQueries,
  } = useProductPageRefreshActions({
    queryClient,
    productPageTab,
    selectedProductId,
    statusGroupBy,
    statusProductId,
    productManagementTab,
    selectedManagementStoryIdForTasks,
  });

  const {
    selectProductArea,
    selectCapabilityForManagement,
    openCreateCapabilityForArea,
    openCreateFeatureForCapability,
    openEditProductArea,
    openEditCapabilityNode,
    requestDeleteHierarchyNode,
    openFeatureInBuilder,
    openStoryInBuilder,
    renderCopyableEntityId,
    editProductFromList,
    openProductDesign,
    openProductOverview,
    openProductStatus,
    openProductDependencies,
    requestArchiveProduct,
    requestResetProductPlan,
    openCreateStoryDialog,
    openEditStoryDialog,
    openCreateTaskDialog,
    openEditTaskDialog,
    requestDeleteWorkItem,
  } = useProductPageActions({
    navigate,
    copiedEntityId,
    setCopiedEntityId,
    setActiveProduct,
    setActiveHierarchyNode,
    setActiveWorkItem,
    setActiveView,
    setStatusProductId,
    setProductPageTab,
    setProductDraft,
    openProductDialog,
    openProductAreaDialog,
    openCapabilityDialog,
    setProductAreaDraft,
    setCapabilityForm,
    setCapabilityDraft,
    setDeleteProductCandidate,
    setDeleteConfirmName,
    setDeleteConfirmArchive,
    setResetPlanCandidate,
    setResetPlanConfirmName,
    setResetPlanConfirmTree,
    setResetPlanDeleteDelivery,
    setDeleteHierarchyCandidate,
    setDeleteHierarchyConfirmName,
    setDeleteHierarchyConfirmChecked,
    setSelectedManagementStoryId,
    setStoryDialogMode,
    setTaskDialogMode,
    setEditingStory,
    setEditingTask,
    setStoryDraft,
    setTaskDraft,
    setDeleteWorkItemCandidate,
    setDeleteWorkItemConfirmName,
    setDeleteWorkItemConfirmChecked,
    setFormError,
  });

  return {
    activeProductAreaId,
    allManagementFeatures,
    allProductTags,
    archiveMutation,
    capabilityDialogMode,
    capabilityDraft,
    capabilityForm,
    capabilityLabelById,
    catalogFilterError,
    catalogFilterMsg,
    closeCapabilityDialog,
    closeProductAreaDialog,
    closeProductDialog,
    createCapabilityMutation,
    createManagementStoryMutation,
    createManagementTaskMutation,
    createProductAreaMutation,
    createProductDependencyMutation,
    createProductMutation,
    deleteConfirmArchive,
    deleteConfirmName,
    deleteConfirmationReady,
    deleteHierarchyCandidate,
    deleteHierarchyConfirmChecked,
    deleteHierarchyConfirmName,
    deleteHierarchyMutation,
    deleteHierarchyReady,
    deleteManagementWorkItemReady,
    deleteManagementWorkItemMutation,
    deleteProductCandidate,
    deleteWorkItemCandidate,
    deleteWorkItemConfirmChecked,
    deleteWorkItemConfirmName,
    dependencyDraft,
    dependencyTargetCapabilityOptions,
    editProductFromList,
    editableCapabilityNodeKindGroups,
    featureStories,
    formError,
    includeDefaultProductsInCatalog,
    isLoading,
    managementCapabilities,
    managementFeatureWorkItemPage,
    managementFeatures,
    managementStoryPageIndex,
    openCapabilityDialog,
    openCreateCapabilityForArea,
    openCreateFeatureForCapability,
    openCreateStoryDialog,
    openCreateTaskDialog,
    openEditCapabilityNode,
    openEditProductArea,
    openEditStoryDialog,
    openEditTaskDialog,
    openFeatureInBuilder,
    openProductDependencies,
    openProductDesign,
    openProductDialog,
    openProductAreaDialog,
    openProductOverview,
    openProductStatus,
    openStoryInBuilder,
    productAreaDialogMode,
    productAreaDraft,
    productAreaForm,
    productAreaProductAreas,
    productDialogMode,
    productDraft,
    productForm,
    productManagementRefreshLabel,
    productManagementTab,
    productNameById,
    productPageTab,
    productSearch,
    productSort,
    productSourceFilter,
    productStatusFilter,
    productTagFilter,
    productTableRows,
    products,
    renderCopyableEntityId,
    requestArchiveProduct,
    requestDeleteHierarchyNode,
    requestDeleteWorkItem,
    requestResetProductPlan,
    resetPlanCandidate,
    resetPlanConfirmName,
    resetPlanConfirmTree,
    resetPlanDeleteDelivery,
    resetPlanReady,
    resetProductPlanMutation,
    scopeSummaryIndex,
    selectCapabilityForManagement,
    selectProductArea,
    selectedCapability,
    selectedCapabilityAllowedKindGroups,
    selectedCapabilityOptions,
    selectedManagementCapabilityTree,
    selectedManagementFeature,
    selectedManagementFeatureNode,
    selectedManagementStory,
    selectedManagementTasks,
    selectedProduct,
    selectedProductArea,
    selectedProductAreaTree,
    selectedProductDependencies,
    selectedProductId,
    setActiveHierarchyNode,
    setActiveProduct,
    setActiveWorkItem,
    setCapabilityDraft,
    setCapabilityForm,
    setDeleteConfirmArchive,
    setDeleteConfirmName,
    setDeleteHierarchyCandidate,
    setDeleteHierarchyConfirmChecked,
    setDeleteHierarchyConfirmName,
    setDeleteProductCandidate,
    setDeleteWorkItemCandidate,
    setDeleteWorkItemConfirmChecked,
    setDeleteWorkItemConfirmName,
    setDependencyDraft,
    setManagementStoryPageIndex,
    setProductAreaDraft,
    setProductAreaForm,
    setProductDraft,
    setProductForm,
    setProductManagementTab,
    setProductPageTab,
    setProductSearch,
    setProductSort,
    setProductSourceFilter,
    setProductTagFilter,
    setProductStatusFilter,
    setResetPlanCandidate,
    setResetPlanConfirmName,
    setResetPlanConfirmTree,
    setResetPlanDeleteDelivery,
    setSelectedManagementStoryId,
    setShowCustomProductsInTable,
    setShowDefaultProductsInTable,
    setStatusDepth,
    setStatusGroupBy,
    setStatusProductId,
    setStoryDialogMode,
    setStoryDraft,
    setTaskDialogMode,
    setTaskDraft,
    showCustomProductsInTable,
    showDefaultProductsInTable,
    statusDepth,
    statusGroupBy,
    statusProductId,
    statusRows,
    statusSummary,
    storyDialogMode,
    storyDraft,
    taskDialogMode,
    taskDraft,
    tree,
    updateCapabilityMutation,
    updateDefaultProductVisibility,
    updateManagementStoryMutation,
    updateManagementTaskMutation,
    updateProductAreaMutation,
    updateProductMutation,
    activeProductPageRefreshLabel,
    activeProductPageRefreshDisabled,
    refreshActiveProductPageTab,
    refreshProductManagementTabQueries,
  };
}

export type ProductListPageController = ReturnType<typeof useProductListPageController>;
