import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  page: { display: "flex", flexDirection: "column", gap: 8, height: "100%" },
  topGrid: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) 320px", gap: 12, minHeight: 0, flex: 1 },
  compactStack: { display: "flex", flexDirection: "column", gap: 12, minHeight: 0, flex: 1 },
  panel: { backgroundColor: "#ffffff", border: "1px solid #d8dee8", borderRadius: 14, minHeight: 0, overflow: "hidden" },
  panelBody: { padding: 16, height: "100%", overflow: "auto" },
  compactPanelBody: { padding: 14, height: "100%", overflow: "auto" },
  sectionTitle: { fontSize: 11, fontWeight: 800, letterSpacing: 0.8, textTransform: "uppercase" as const, color: "#64748b", marginBottom: 10 },
  sectionHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, marginBottom: 10 },
  transcript: { display: "flex", flexDirection: "column", gap: 10 },
  bubbleUser: { alignSelf: "flex-end", maxWidth: "80%", backgroundColor: "#2563eb", color: "#ffffff", borderRadius: 14, padding: "10px 12px", whiteSpace: "pre-wrap" as const, fontSize: 13, lineHeight: 1.45 },
  bubbleAssistant: { alignSelf: "flex-start", maxWidth: "84%", backgroundColor: "#f8fafc", color: "#111827", border: "1px solid #e2e8f0", borderRadius: 14, padding: "10px 12px", fontSize: 13, lineHeight: 1.45 },
  bubblePending: { alignSelf: "flex-end", maxWidth: "80%", backgroundColor: "#eff6ff", color: "#1e3a8a", borderRadius: 14, padding: "10px 12px", whiteSpace: "pre-wrap" as const, border: "1px dashed #93c5fd", opacity: 0.95, fontSize: 13, lineHeight: 1.45 },
  messageText: { fontSize: 13, lineHeight: 1.45, color: "#111827" },
  bubbleMeta: { display: "block", marginTop: 8, fontSize: 11, color: "#94a3b8" },
  composerWrap: { display: "flex", flexDirection: "column", gap: 10, borderTop: "1px solid #d8dee8", paddingTop: 12, marginTop: 12 },
  textarea: { width: "100%", minHeight: 92, resize: "vertical" as const, padding: "12px 14px", borderRadius: 12, backgroundColor: "#ffffff", border: "1px solid #cbd5e1", color: "#111827", fontSize: 14, boxSizing: "border-box" as const },
  actionRow: { display: "flex", flexWrap: "wrap" as const, gap: 10, alignItems: "center" },
  btn: { padding: "9px 14px", fontSize: 13, backgroundColor: "#2563eb", color: "#ffffff", border: "1px solid #1d4ed8", borderRadius: 10, cursor: "pointer", fontWeight: 700 },
  btnGhost: { padding: "9px 14px", fontSize: 13, backgroundColor: "#f8fafc", color: "#1e3a8a", border: "1px solid #cbd5e1", borderRadius: 10, cursor: "pointer", fontWeight: 700 },
  btnDanger: { padding: "9px 14px", fontSize: 13, backgroundColor: "#dc2626", color: "#ffffff", border: "1px solid #b91c1c", borderRadius: 10, cursor: "pointer", fontWeight: 700 },
  status: { fontSize: 12, color: "#64748b" },
  sideCard: { border: "1px solid #d8dee8", borderRadius: 12, backgroundColor: "#ffffff", padding: 12, marginBottom: 12 },
  label: { fontSize: 12, color: "#64748b", display: "block", marginBottom: 6 },
  input: { width: "100%", padding: "9px 10px", backgroundColor: "#ffffff", border: "1px solid #cbd5e1", borderRadius: 10, color: "#111827", fontSize: 13, boxSizing: "border-box" as const },
  select: { width: "100%", padding: "9px 10px", backgroundColor: "#ffffff", border: "1px solid #cbd5e1", borderRadius: 10, color: "#111827", fontSize: 13, boxSizing: "border-box" as const },
  helper: { fontSize: 12, color: "#64748b", lineHeight: 1.45 },
  chipRow: { display: "flex", flexWrap: "wrap" as const, gap: 8, marginTop: 10 },
  chip: { padding: "5px 8px", borderRadius: 999, backgroundColor: "#e2e8f0", color: "#334155", fontSize: 11, fontWeight: 700 },
  warning: { color: "#a16207", fontSize: 12, lineHeight: 1.45 },
  error: { color: "#b91c1c", fontSize: 12, lineHeight: 1.45 },
  success: { color: "#15803d", fontSize: 12, lineHeight: 1.45 },
  list: { display: "flex", flexDirection: "column", gap: 8, marginTop: 10 },
  listItem: { borderRadius: 10, border: "1px solid #d8dee8", backgroundColor: "#f8fafc", padding: 10 },
  listItemTitle: { fontSize: 12, fontWeight: 700, color: "#111827", marginBottom: 4 },
  listItemMeta: { fontSize: 12, color: "#475569", whiteSpace: "pre-wrap" as const },
  card: { border: "1px solid #d8dee8", backgroundColor: "#ffffff", borderRadius: 12, padding: 12, marginTop: 10 },
  voiceReviewCard: { border: "1px solid #bfdbfe", backgroundColor: "#eff6ff", borderRadius: 12, padding: 12, marginBottom: 10 },
  voiceReviewHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, marginBottom: 10, flexWrap: "wrap" as const },
  voiceReviewTitle: { fontSize: 13, fontWeight: 800, color: "#111827" },
  cardTitle: { fontSize: 13, fontWeight: 800, color: "#111827", marginBottom: 8 },
  cardSection: { marginTop: 10 },
  diffRow: { display: "grid", gridTemplateColumns: "24px minmax(0, 1fr)", gap: 8, alignItems: "start", padding: "8px 0", borderTop: "1px solid #e2e8f0" },
  diffSymbolAdd: { color: "#15803d", fontWeight: 800, fontSize: 16, lineHeight: 1.2 },
  diffSymbolUpdate: { color: "#1d4ed8", fontWeight: 800, fontSize: 16, lineHeight: 1.2 },
  diffSymbolWarn: { color: "#a16207", fontWeight: 800, fontSize: 16, lineHeight: 1.2 },
  diffPrimary: { fontSize: 13, color: "#111827", fontWeight: 700 },
  diffSecondary: { fontSize: 12, color: "#475569", marginTop: 4, whiteSpace: "pre-wrap" as const },
  treePanel: { border: "1px solid #d8dee8", backgroundColor: "#f8fafc", borderRadius: 12, padding: 12, marginTop: 10 },
  treeNode: { marginLeft: 0 },
  treeSummary: { cursor: "pointer", listStyle: "none", fontSize: 13, color: "#111827", fontWeight: 700, padding: "4px 0" },
  treeChildren: { marginLeft: 18, borderLeft: "1px solid #cbd5e1", paddingLeft: 10 },
  treeLeaf: { fontSize: 13, color: "#334155", padding: "4px 0" },
  treeMeta: { fontSize: 11, color: "#64748b", marginLeft: 6 },
  treeButton: { width: "100%", textAlign: "left" as const, background: "transparent", border: "1px solid transparent", borderRadius: 8, color: "#111827", padding: "6px 8px", cursor: "pointer", fontSize: 13, fontWeight: 700 },
  treeButtonSelected: { border: "1px solid #2563eb", backgroundColor: "#eff6ff" },
  treeExplorer: { display: "flex", flexDirection: "column", gap: 4 },
  treeToolbar: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" as const, marginBottom: 12 },
  treeToolbarSpacer: { flex: 1 },
  treeLevel: { display: "flex", flexDirection: "column", gap: 6 },
  treeRow: { display: "grid", gridTemplateColumns: "26px minmax(0, 1fr)", gap: 8, alignItems: "start" },
  treeToggle: { width: 26, height: 26, borderRadius: 8, border: "1px solid #cbd5e1", backgroundColor: "#ffffff", color: "#334155", cursor: "pointer", fontSize: 12, fontWeight: 800, padding: 0 },
  treeToggleGhost: { width: 26, height: 26, borderRadius: 8, border: "1px solid transparent", backgroundColor: "transparent", color: "#94a3b8", padding: 0 },
  treeCard: { width: "100%", textAlign: "left" as const, border: "1px solid #d8dee8", backgroundColor: "#ffffff", color: "#111827", borderRadius: 12, padding: "10px 12px", cursor: "pointer" },
  treeCardSelected: { border: "1px solid #2563eb", backgroundColor: "#eff6ff", boxShadow: "inset 0 0 0 1px rgba(37,99,235,0.16)" },
  treeCardHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10, flexWrap: "wrap" as const },
  treeCardTitle: { fontSize: 14, fontWeight: 800, color: "#111827" },
  treeCardMetaRow: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" as const, marginTop: 6 },
  treeTypeBadge: { fontSize: 11, fontWeight: 800, textTransform: "uppercase" as const, letterSpacing: 0.4, color: "#1d4ed8", backgroundColor: "#dbeafe", borderRadius: 999, padding: "3px 8px" },
  treeCountBadge: { fontSize: 11, fontWeight: 700, color: "#475569", backgroundColor: "#e2e8f0", borderRadius: 999, padding: "3px 8px" },
  treeRowChildren: { marginLeft: 18, paddingLeft: 16, borderLeft: "1px solid #cbd5e1", display: "flex", flexDirection: "column", gap: 6 },
  inlineButtonRow: { display: "flex", gap: 8, marginTop: 12, flexWrap: "wrap" as const },
  viewToggleRow: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" as const },
  draftWorkspace: { display: "grid", gridTemplateColumns: "minmax(0, 1.6fr) minmax(260px, 0.9fr)", gap: 12, flex: 1, minHeight: 0 },
  draftWorkspaceMain: { display: "flex", flexDirection: "column", minHeight: 0 },
  draftWorkspaceSide: { display: "flex", flexDirection: "column", gap: 12, minHeight: 0 },
  draftCanvas: { border: "1px solid #d8dee8", backgroundColor: "#ffffff", borderRadius: 12, padding: 14, flex: 1, minHeight: 0, overflow: "auto" },
  draftCanvasHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, marginBottom: 10, flexWrap: "wrap" as const },
  draftCanvasTitle: { fontSize: 14, fontWeight: 800, color: "#111827" },
  emptyState: { border: "1px dashed #cbd5e1", borderRadius: 12, padding: 18, color: "#64748b", backgroundColor: "#f8fafc", lineHeight: 1.5 },
  metricGrid: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 8, marginTop: 10 },
  metricCard: { borderRadius: 12, border: "1px solid #d8dee8", backgroundColor: "#f8fafc", padding: 10 },
  metricLabel: { fontSize: 11, color: "#64748b", textTransform: "uppercase" as const, letterSpacing: 0.5 },
  metricValue: { marginTop: 6, fontSize: 20, fontWeight: 800, color: "#111827" },
  readinessBanner: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, padding: "10px 12px", borderRadius: 12, border: "1px solid #d8dee8", backgroundColor: "#f8fafc", marginBottom: 12, flexWrap: "wrap" as const },
  readinessScore: { fontSize: 24, fontWeight: 800, color: "#111827" },
  readinessMeta: { fontSize: 12, color: "#64748b" },
  issueList: { display: "flex", flexDirection: "column", gap: 8, marginTop: 10 },
  issueCard: { borderRadius: 10, border: "1px solid #d8dee8", backgroundColor: "#f8fafc", padding: 10 },
  issueCardWarn: { borderRadius: 10, border: "1px solid #fde68a", backgroundColor: "#fffbeb", padding: 10 },
  issueCardOk: { borderRadius: 10, border: "1px solid #bbf7d0", backgroundColor: "#f0fdf4", padding: 10 },
  issueTitle: { fontSize: 12, fontWeight: 800, color: "#111827", marginBottom: 4 },
  issueDetail: { fontSize: 12, color: "#475569", lineHeight: 1.45 },
  promptList: { display: "flex", flexDirection: "column", gap: 8, marginTop: 10 },
  promptButton: { width: "100%", textAlign: "left" as const, padding: "9px 10px", borderRadius: 10, border: "1px solid #cbd5e1", backgroundColor: "#f8fafc", color: "#1e3a8a", cursor: "pointer", fontSize: 12, lineHeight: 1.45 },
  pathText: { fontSize: 12, color: "#64748b", lineHeight: 1.4, marginTop: 8 },
  sectionDivider: { height: 1, backgroundColor: "#e2e8f0", margin: "12px 0" },
  fieldGroup: { display: "flex", flexDirection: "column", gap: 8, marginTop: 10 },
  compactTextarea: { width: "100%", minHeight: 70, resize: "vertical" as const, padding: "9px 10px", borderRadius: 10, backgroundColor: "#ffffff", border: "1px solid #cbd5e1", color: "#111827", fontSize: 13, boxSizing: "border-box" as const },
  mutedButton: { padding: "9px 14px", fontSize: 13, backgroundColor: "#f8fafc", color: "#1e3a8a", border: "1px solid #cbd5e1", borderRadius: 10, cursor: "pointer", fontWeight: 700 },
  statusBanner: { border: "1px solid #d8dee8", backgroundColor: "#f8fafc", borderRadius: 12, padding: "10px 12px", marginBottom: 12, display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, flexWrap: "wrap" as const },
  statusBannerStrong: { fontSize: 13, fontWeight: 800, color: "#111827" },
  statusBannerMeta: { fontSize: 12, color: "#475569", lineHeight: 1.45, marginTop: 4 },
  compactControlStrip: { display: "flex", gap: 8, flexWrap: "wrap" as const, alignItems: "center", marginBottom: 12 },
  compactSummaryCard: { border: "1px solid #d8dee8", backgroundColor: "#ffffff", borderRadius: 12, padding: 12 },
  compactSummaryGrid: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 8 },
  compactSummaryItem: { borderRadius: 10, backgroundColor: "#f8fafc", border: "1px solid #e2e8f0", padding: "10px 12px" },
  compactSummaryLabel: { fontSize: 11, color: "#64748b", textTransform: "uppercase" as const, letterSpacing: 0.5 },
  compactSummaryValue: { fontSize: 13, fontWeight: 800, color: "#111827", marginTop: 6, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" as const },
  composerScopeCard: { border: "1px solid #d8dee8", backgroundColor: "#ffffff", borderRadius: 12, padding: 10 },
  composerScopeTitle: { fontSize: 12, fontWeight: 800, color: "#111827", marginBottom: 6 },
  modalOverlay: { position: "fixed" as const, inset: 0, backgroundColor: "rgba(5, 8, 12, 0.72)", display: "flex", alignItems: "center", justifyContent: "center", padding: 24, zIndex: 50 },
  modalCard: { width: "min(720px, 100%)", maxHeight: "80vh", overflow: "auto" as const, backgroundColor: "#ffffff", border: "1px solid #d8dee8", borderRadius: 16, padding: 16, boxShadow: "0 18px 60px rgba(15,23,42,0.18)" },
  modalHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, marginBottom: 12 },
  modalTitle: { fontSize: 18, fontWeight: 800, color: "#111827" },
  iconButton: { padding: "9px 12px", fontSize: 13, backgroundColor: "#f8fafc", color: "#1e3a8a", border: "1px solid #cbd5e1", borderRadius: 10, cursor: "pointer", fontWeight: 700, whiteSpace: "nowrap" as const },
};
