import { useQueryClient } from "@tanstack/react-query";
import { useWorkspaceStore } from "../../../state/workspaceStore";
import { useUIStore } from "../../../state/uiStore";
import { useWorkItemActionMutations } from "./useWorkItemActionMutations";
import { useWorkItemBacklogApprovalActions } from "./useWorkItemBacklogApprovalActions";
import { useWorkItemBacklogView } from "./useWorkItemBacklogView";
import { useWorkItemCrudMutations } from "./useWorkItemCrudMutations";
import { useWorkItemListPageState } from "./useWorkItemListPageState";
import { useWorkItemPageSync } from "./useWorkItemPageSync";
import { useWorkItemReviewSignals } from "./useWorkItemReviewSignals";
import { useWorkItemResolvedRepository } from "./useWorkItemResolvedRepository";
import { useWorkItemScopeData } from "./useWorkItemScopeData";
import { useWorkItemScopeDisplay } from "./useWorkItemScopeDisplay";
import { useWorkItemTaskInvalidation } from "./useWorkItemTaskInvalidation";
import { useWorkItemWorkspaceAssignment } from "./useWorkItemWorkspaceAssignment";
import { useWorkItemWorkspaceQueries } from "./useWorkItemWorkspaceQueries";

export function useWorkItemListPageController() {
  const queryClient = useQueryClient();
  const {
    activeProductId,
    activeProductAreaId,
    activeCapabilityId,
    activeNodeId,
    activeNodeType,
    activeWorkItemId,
    setActiveProduct,
    setActiveWorkItem,
  } = useWorkspaceStore();
  const { workItemWorkspaceTab, setWorkItemWorkspaceTab, workItemCreateDialogOpen, openWorkItemCreateDialog, closeWorkItemCreateDialog, setActiveView } = useUIStore();

  const {
    statusFilter, setStatusFilter, workItemPageIndex, setWorkItemPageIndex,
    backlogViewportRef, backlogScrollTop, setBacklogScrollTop,
    backlogViewportHeight, setBacklogViewportHeight, showCreateForm, setShowCreateForm,
    isEditingWorkItem, setIsEditingWorkItem, draggedWorkItemId, setDraggedWorkItemId,
    workItemOrderIds, setWorkItemOrderIds, formError, setFormError,
    actionError, setActionError, actionInfo, setActionInfo,
    activeWorkflowRunId, setActiveWorkflowRunId, selectedExternalCliRunId,
    setSelectedExternalCliRunId, selectedArtifactStage, setSelectedArtifactStage,
    artifactModalArtifact, setArtifactModalArtifact, openOverflowWorkItemId,
    setOpenOverflowWorkItemId, selectedBacklogItemIds, setSelectedBacklogItemIds,
    pendingRowActionIds, setPendingRowActionIds, bulkActionInFlight,
    setBulkActionInFlight, createForm, setCreateForm, workItemDraft, setWorkItemDraft,
  } = useWorkItemListPageState();

  const {
    products,
    productsLoading,
    selectedProductId,
    workItemsScopeQueryKey,
    workItemsQueryKey,
    workItemPage,
    isLoading,
    productAreaById,
    capabilityById,
    repositories,
    filteredWorkItems,
    selectedWorkItemId,
    selectedWorkItem,
  } = useWorkItemScopeData({
    activeProductId,
    activeProductAreaId,
    activeNodeId,
    activeNodeType,
    activeWorkItemId,
    statusFilter,
    workItemPageIndex,
  });

  const {
    latestWorkflowRun,
    workflowRunId,
    subWorkItems,
    approvals,
    artifacts,
    resolvedRepositoryFromQuery,
    artifactModalContent,
    findings,
    teamAssignments,
    agentTeams,
    teamMemberships,
    agentDefinitions,
    workflowPolicies,
    modelBindings,
    modelDefinitions,
    providers,
    workflowHistory,
    activeWorkflowStage,
    agentRuns,
    agentModelCalls,
    externalCliRuns,
  } = useWorkItemWorkspaceQueries({
    selectedWorkItemId,
    activeWorkflowRunId,
    artifactModalArtifact,
  });

  useWorkItemPageSync({
    productsLoading,
    activeProductId,
    selectedProductId,
    setActiveProduct,
    selectedProductScopeId: selectedProductId,
    activeNodeId,
    activeNodeType,
    statusFilter,
    setWorkItemPageIndex,
    setSelectedBacklogItemIds,
    workItemPageIndex,
    backlogViewportRef,
    setBacklogScrollTop,
    setBacklogViewportHeight,
    workItemWorkspaceTab,
    selectedWorkItemId,
    activeWorkItemId,
    setActiveWorkItem,
    activeProductAreaId,
    activeCapabilityId,
    setActionError,
    setActionInfo,
    setActiveWorkflowRunId,
    setSelectedArtifactStage,
    setOpenOverflowWorkItemId,
    selectedWorkItem,
    setWorkItemDraft,
    filteredWorkItems,
    setWorkItemOrderIds,
    showCreateForm,
    workItemCreateDialogOpen,
    setFormError,
    setSelectedExternalCliRunId,
  });

  const invalidateTasks = useWorkItemTaskInvalidation({
    queryClient,
    activeProductId,
    selectedWorkItemId,
    workflowRunId,
    workItemsScopeQueryKey,
    workItemsQueryKey,
  });

  const {
    createMutation,
    updateWorkItemMutation,
    deleteMutation,
  } = useWorkItemCrudMutations({
    queryClient,
    activeProductId,
    activeProductAreaId,
    activeCapabilityId,
    activeNodeId,
    activeNodeType,
    selectedWorkItemId,
    createForm,
    setCreateForm,
    workItemDraft,
    setWorkItemOrderIds,
    setActiveWorkItem,
    setShowCreateForm,
    closeWorkItemCreateDialog,
    setWorkItemWorkspaceTab,
    setIsEditingWorkItem,
    setFormError,
    workItemsQueryKey,
    activeProductSidebarQueryKey: ["sidebarWorkItems", activeProductId],
    workItemPageIndex,
    invalidateTasks,
  });

  const {
    approveMutation,
    rejectMutation,
    workflowMutation,
    externalCliMutation,
    planApprovalMutation,
    planRejectMutation,
    testReviewApproveMutation,
    testReviewRejectMutation,
    failWorkflowRunMutation,
    restartWorkflowMutation,
    reorderWorkItemsMutation,
  } = useWorkItemActionMutations({
    queryClient,
    selectedWorkItemId,
    workflowRunId,
    setActiveWorkflowRunId,
    setSelectedExternalCliRunId,
    setActionError,
    setActionInfo,
    setWorkItemWorkspaceTab,
    invalidateTasks,
  });
  const { selectedWorkItemSummary, resolvedRepository } = useWorkItemResolvedRepository({
    filteredWorkItems,
    repositories,
    resolvedRepositoryFromQuery,
    selectedWorkItem,
    selectedWorkItemId,
  });
  const {
    createWorkspace,
    isCreateWorkspacePending,
    workspaceAssignmentPanel,
  } = useWorkItemWorkspaceAssignment({
    queryClient,
    activeProductId,
    activeProductAreaId,
    selectedWorkItemId,
    selectedWorkItem: selectedWorkItemSummary,
    repositories,
    resolvedRepository,
    workItemsScopeQueryKey,
    workItemsQueryKey,
    setActionError,
    setActionInfo,
    setActiveView,
    invalidateTasks,
  });
  const {
    selectedDagNodeId,
    workflowElapsedLabel,
    isStaleRun,
    selectedDagNode,
    stageRuns,
    artifactsByAgentRunId,
    modelCallsByAgentRunId,
    workflowModelUsage,
    completedStages,
    dagNodeById,
    laneStatusById,
    latestApproval,
    latestArtifact,
    latestExternalCliRun,
    activeExternalCliRunId,
    activeExternalCliRun,
    externalCliRunEvents,
    latestExternalCliEvent,
    externalCliTerminalOutput,
    findingSeverityCounts,
    topArtifactTypes,
    workflowReadiness,
    stageHistoryForFocusedStage,
  } = useWorkItemReviewSignals({
    selectedArtifactStage,
    activeWorkflowStage,
    latestWorkflowRun,
    workflowRunId,
    workflowHistory,
    agentRuns,
    agentModelCalls,
    artifacts,
    approvals,
    findings,
    externalCliRuns,
    selectedExternalCliRunId,
    selectedWorkItem: selectedWorkItemSummary,
    teamAssignments,
    agentTeams,
    teamMemberships,
    agentDefinitions,
    workflowPolicies,
    modelBindings,
    modelDefinitions,
    providers,
    resolvedRepository,
  });
  const {
    activeProduct,
    activeProductArea,
    activeCapability,
    scopeDescriptor,
    createWorkItemScopeLabel,
    workItemOwnerMap,
  } = useWorkItemScopeDisplay({
    products,
    activeProductId,
    activeProductAreaId,
    activeCapabilityId,
    productAreaById,
    capabilityById,
    filteredWorkItems,
    createParentWorkItemId: createForm.parentWorkItemId,
  });
  const {
    orderedWorkItems,
    backlogWindow,
    hasNextWorkItemPage,
    workItemPageStart,
    workItemPageEnd,
    backlogRenderedRangeLabel,
    selectedBacklogItems,
    latestWorkflowRunByWorkItemId,
  } = useWorkItemBacklogView({
    filteredWorkItems,
    workItemOrderIds,
    backlogScrollTop,
    backlogViewportHeight,
    workItemPage,
    workItemPageIndex,
    selectedBacklogItemIds,
    isBacklogActive: workItemWorkspaceTab === "backlog",
  });
  const {
    isRowActionPending,
    runRowApprovalAction,
    runBulkApprovalAction,
  } = useWorkItemBacklogApprovalActions({
    selectedBacklogItemIds,
    setSelectedBacklogItemIds,
    pendingRowActionIds,
    setPendingRowActionIds,
    bulkActionInFlight,
    setBulkActionInFlight,
    setActionError,
    invalidateTasks,
  });
  const stageLabel = activeWorkflowStage ? activeWorkflowStage.replace(/_/g, " ") : null;
  const externalCliProviderInFlight = externalCliMutation.isPending ? externalCliMutation.variables : null;

  return {
    actionError,
    actionInfo,
    activeCapability,
    activeExternalCliRun,
    activeExternalCliRunId,
    activeProduct,
    activeProductArea,
    activeProductId,
    activeWorkflowStage,
    approveMutation,
    approvals,
    artifactModalArtifact,
    artifactModalContent,
    artifacts,
    artifactsByAgentRunId,
    backlogRenderedRangeLabel,
    backlogViewportRef,
    backlogWindow,
    bulkActionInFlight,
    closeWorkItemCreateDialog,
    completedStages,
    createForm,
    createMutation,
    createWorkspace,
    createWorkItemScopeLabel,
    dagNodeById,
    deleteMutation,
    draggedWorkItemId,
    externalCliMutation,
    externalCliProviderInFlight,
    externalCliRunEvents,
    externalCliRuns,
    externalCliTerminalOutput,
    failWorkflowRunMutation,
    findingSeverityCounts,
    findings,
    formError,
    hasNextWorkItemPage,
    isCreateWorkspacePending,
    isEditingWorkItem,
    isLoading,
    isRowActionPending,
    isStaleRun,
    laneStatusById,
    latestApproval,
    latestArtifact,
    latestExternalCliEvent,
    latestExternalCliRun,
    latestWorkflowRun,
    latestWorkflowRunByWorkItemId,
    modelCallsByAgentRunId,
    openOverflowWorkItemId,
    openWorkItemCreateDialog,
    orderedWorkItems,
    planApprovalMutation,
    planRejectMutation,
    rejectMutation,
    reorderWorkItemsMutation,
    resolvedRepository,
    restartWorkflowMutation,
    runBulkApprovalAction,
    runRowApprovalAction,
    scopeDescriptor,
    selectedArtifactStage,
    selectedBacklogItemIds,
    selectedBacklogItems,
    selectedDagNode,
    selectedDagNodeId,
    selectedExternalCliRunId,
    selectedWorkItemId,
    selectedWorkItemSummary,
    setActiveWorkItem,
    setArtifactModalArtifact,
    setBacklogScrollTop,
    setCreateForm,
    setDraggedWorkItemId,
    setIsEditingWorkItem,
    setOpenOverflowWorkItemId,
    setSelectedArtifactStage,
    setSelectedBacklogItemIds,
    setSelectedExternalCliRunId,
    setShowCreateForm,
    setStatusFilter,
    setWorkItemDraft,
    setWorkItemOrderIds,
    setWorkItemPageIndex,
    setWorkItemWorkspaceTab,
    showCreateForm,
    stageRuns,
    stageHistoryForFocusedStage,
    stageLabel,
    statusFilter,
    subWorkItems,
    testReviewApproveMutation,
    testReviewRejectMutation,
    topArtifactTypes,
    updateWorkItemMutation,
    workItemCreateDialogOpen,
    workItemDraft,
    workItemOrderIds,
    workItemOwnerMap,
    workItemPageEnd,
    workItemPageIndex,
    workItemPageStart,
    workItemWorkspaceTab,
    workflowElapsedLabel,
    workflowHistory,
    workflowModelUsage,
    workflowMutation,
    workflowReadiness,
    workflowRunId,
    workspaceAssignmentPanel,
  };
}

export type WorkItemListPageController = ReturnType<typeof useWorkItemListPageController>;
