import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  page: { display: "flex", flexDirection: "column", gap: 12, height: "100%" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10 },
  titleBlock: { display: "flex", flexDirection: "column", gap: 3 },
  title: { fontSize: 18, fontWeight: 800, color: "#f3f3f3", margin: 0 },
  subtitle: { fontSize: 12, color: "#8f96a3" },
  panel: { backgroundColor: "#212327", border: "1px solid #32353d", borderRadius: 12, minHeight: 0, overflow: "hidden", flex: 1 },
  panelInner: { padding: 14, height: "100%", overflow: "auto" },
  tabBar: { display: "flex", gap: 8, marginBottom: 14, borderBottom: "1px solid #32353d", paddingBottom: 10 },
  tab: { padding: "7px 12px", fontSize: 12, fontWeight: 700, borderRadius: 8, border: "1px solid #3b4049", backgroundColor: "#2c3139", color: "#cfd6e4", cursor: "pointer" },
  tabActive: { padding: "7px 12px", fontSize: 12, fontWeight: 700, borderRadius: 8, border: "1px solid #0e639c", backgroundColor: "#173247", color: "#ffffff", cursor: "pointer" },
  btn: { padding: "7px 12px", fontSize: 12, backgroundColor: "#0e639c", color: "#fff", border: "none", borderRadius: 8, cursor: "pointer" },
  btnDanger: { padding: "6px 10px", fontSize: 12, backgroundColor: "#6c2020", color: "#fff", border: "none", borderRadius: 8, cursor: "pointer" },
  ghostBtn: { padding: "6px 10px", fontSize: 12, backgroundColor: "#2c3139", color: "#e0e0e0", border: "1px solid #3b4049", borderRadius: 8, cursor: "pointer" },
  sectionTitle: { fontSize: 12, fontWeight: 700, letterSpacing: 1, textTransform: "uppercase" as const, color: "#8f96a3", marginBottom: 10, display: "flex", alignItems: "center", justifyContent: "space-between" },
  filterSelect: { padding: "7px 10px", fontSize: 12, backgroundColor: "#181a1f", border: "1px solid #3c4048", borderRadius: 8, color: "#e0e0e0", width: "100%", marginBottom: 12 },
  taskList: { display: "flex", flexDirection: "column", gap: 8 },
  virtualTaskViewport: { maxHeight: "calc(100vh - 355px)", minHeight: 260, overflowY: "auto" as const, paddingRight: 4 },
  virtualTaskSpacer: { display: "flex", flexDirection: "column", gap: 8 },
  taskCard: { padding: 12, border: "1px solid #32353d", borderRadius: 10, backgroundColor: "#26292f", cursor: "pointer" },
  taskCardActive: { padding: 12, border: "1px solid #0e639c", borderRadius: 10, background: "linear-gradient(135deg, rgba(14,99,156,0.18), rgba(38,41,47,1))", cursor: "pointer" },
  taskRowCard: { display: "grid", gridTemplateColumns: "minmax(0, 1.6fr) minmax(260px, 1fr) auto", gap: 12, alignItems: "center" },
  taskMain: { display: "flex", flexDirection: "column", gap: 4, minWidth: 0 },
  taskTitle: { fontSize: 13, fontWeight: 700, color: "#f3f3f3", margin: 0, whiteSpace: "nowrap" as const, overflow: "hidden", textOverflow: "ellipsis" },
  taskMeta: { fontSize: 11, color: "#8f96a3", display: "flex", gap: 8, flexWrap: "wrap" },
  ownerRow: { display: "flex", gap: 8, flexWrap: "wrap" as const, alignItems: "center" },
  ownerBadge: { fontSize: 10, fontWeight: 700, padding: "2px 8px", borderRadius: 999, border: "1px solid #36506f", backgroundColor: "#1a2736", color: "#8fc8ff" },
  ownerBadgeRoot: { fontSize: 10, fontWeight: 700, padding: "2px 8px", borderRadius: 999, border: "1px solid #5a5034", backgroundColor: "#2a2619", color: "#e7c77a" },
  ownerPath: { fontSize: 11, color: "#aeb8c8", whiteSpace: "nowrap" as const, overflow: "hidden", textOverflow: "ellipsis" },
  badge: { fontSize: 11, padding: "2px 8px", borderRadius: 10, display: "inline-block" },
  badgeRow: { display: "flex", gap: 8, flexWrap: "wrap" as const, alignItems: "center" },
  taskStatusLine: { fontSize: 12, color: "#cfd6e4", display: "flex", flexDirection: "column", gap: 4, minWidth: 0 },
  taskStatusSummary: { whiteSpace: "nowrap" as const, overflow: "hidden", textOverflow: "ellipsis" },
  taskActions: { display: "flex", gap: 8, alignItems: "center", justifyContent: "flex-end" },
  overflowWrap: { position: "relative" as const },
  overflowMenu: { position: "absolute" as const, top: "calc(100% + 6px)", right: 0, minWidth: 140, backgroundColor: "#1b1d22", border: "1px solid #32353d", borderRadius: 10, boxShadow: "0 12px 28px rgba(0,0,0,0.35)", padding: 6, zIndex: 10, display: "flex", flexDirection: "column", gap: 4 },
  overflowMenuItem: { padding: "7px 10px", fontSize: 12, backgroundColor: "transparent", color: "#e0e0e0", border: "none", borderRadius: 8, textAlign: "left" as const, cursor: "pointer" },
  overflowMenuItemDanger: { padding: "7px 10px", fontSize: 12, backgroundColor: "transparent", color: "#ff9b9b", border: "none", borderRadius: 8, textAlign: "left" as const, cursor: "pointer" },
  detailTitle: { fontSize: 22, fontWeight: 800, color: "#ffffff", marginBottom: 8 },
  detailCard: { backgroundColor: "#26292f", border: "1px solid #32353d", borderRadius: 12, padding: 14, marginBottom: 12 },
  detailLabel: { fontSize: 11, color: "#8f96a3", textTransform: "uppercase" as const, marginBottom: 4 },
  detailValue: { fontSize: 13, color: "#f3f3f3", lineHeight: 1.5 },
  input: { width: "100%", padding: "9px 12px", backgroundColor: "#181a1f", border: "1px solid #3c4048", borderRadius: 8, color: "#e0e0e0", fontSize: 13, marginBottom: 10, boxSizing: "border-box" as const },
  textarea: { width: "100%", padding: "9px 12px", backgroundColor: "#181a1f", border: "1px solid #3c4048", borderRadius: 8, color: "#e0e0e0", fontSize: 13, marginBottom: 10, minHeight: 76, resize: "vertical" as const, boxSizing: "border-box" as const },
  row: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  warning: { color: "#ff7b72", fontSize: 12, marginBottom: 10 },
  previewBox: { whiteSpace: "pre-wrap" as const, fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace", fontSize: 12, lineHeight: 1.5, color: "#d7deea", backgroundColor: "#181a1f", border: "1px solid #3c4048", borderRadius: 8, padding: 10, maxHeight: 320, overflow: "auto" as const },
  dagWrap: { border: "1px solid #3c4048", borderRadius: 8, backgroundColor: "#181a1f", overflowX: "auto" as const, padding: 8, marginBottom: 10 },
  dagLegend: { display: "flex", gap: 10, flexWrap: "wrap" as const, marginBottom: 8, fontSize: 11, color: "#8f96a3" },
  dagLegendItem: { display: "inline-flex", alignItems: "center", gap: 6 },
  readinessCard: { backgroundColor: "#1f242d", border: "1px solid #323f52", borderRadius: 12, padding: 12, marginBottom: 12 },
  readinessHeading: { fontSize: 12, fontWeight: 700, color: "#d8e6ff", marginBottom: 8, textTransform: "uppercase" as const, letterSpacing: 0.8 },
  readinessItem: { fontSize: 12, color: "#d0d7e4", marginBottom: 5 },
  readinessOk: { color: "#4ec9b0", fontWeight: 700 as const },
  readinessWarn: { color: "#d7ba7d", fontWeight: 700 as const },
  readinessBlocker: { color: "#ff7b72", fontWeight: 700 as const },
  list: { display: "flex", flexDirection: "column", gap: 8 },
  listItem: { backgroundColor: "#1b1d22", border: "1px solid #2d3139", borderRadius: 10, padding: 10 },
  smallText: { fontSize: 11, color: "#8f96a3", marginTop: 4 },
  empty: { textAlign: "center" as const, color: "#666", padding: 40, fontSize: 14 },
  dropTarget: { outline: "1px dashed #0e639c", outlineOffset: 2 },
  dragHandle: { fontSize: 13, color: "#8f96a3", cursor: "grab", userSelect: "none" as const, padding: "2px 4px" },
  modalBackdrop: { position: "fixed", inset: 0, backgroundColor: "rgba(8, 10, 14, 0.72)", display: "flex", alignItems: "center", justifyContent: "center", padding: 24, zIndex: 40 },
  modal: { width: "min(760px, 100%)", maxHeight: "80vh", backgroundColor: "#212327", border: "1px solid #32353d", borderRadius: 14, overflow: "hidden", boxShadow: "0 24px 60px rgba(0,0,0,0.45)" },
  modalHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, padding: "14px 16px", borderBottom: "1px solid #32353d" },
  modalTitle: { fontSize: 14, fontWeight: 800, color: "#f3f3f3" },
  modalBody: { padding: 16, maxHeight: "calc(80vh - 61px)", overflow: "auto" },
  errorText: { fontSize: 12, color: "#ff7b72", marginBottom: 10 },
  infoCard: { backgroundColor: "#1b2330", border: "1px solid #32445e", borderRadius: 10, padding: 10, marginTop: 10 },
  traceStepCard: { backgroundColor: "#1b1f27", border: "1px solid #303742", borderRadius: 12, padding: 12, marginBottom: 10 },
  traceStepHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 },
  traceStepTitle: { fontSize: 13, fontWeight: 800, color: "#eef3fb" },
  traceStepMeta: { fontSize: 11, color: "#8f96a3" },
  traceEventList: { display: "flex", flexDirection: "column", gap: 8 },
  traceEventCard: { borderRadius: 10, padding: 10, border: "1px solid #384456", backgroundColor: "#1a2230" },
  traceEventCardError: { borderRadius: 10, padding: 10, border: "1px solid #5a2f35", backgroundColor: "#2b1d22" },
  traceEventKind: { fontSize: 11, fontWeight: 700, color: "#d0d7e4", textTransform: "uppercase" as const, letterSpacing: 0.6, marginBottom: 4 },
  traceEventPayload: { whiteSpace: "pre-wrap" as const, fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace", fontSize: 12, lineHeight: 1.45, color: "#d7deea", margin: 0 },
  terminalOutput: { whiteSpace: "pre-wrap" as const, fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace", fontSize: 12, lineHeight: 1.45, color: "#d7deea", backgroundColor: "#0f1115", border: "1px solid #303742", borderRadius: 8, padding: 12, margin: 0, maxHeight: 520, overflow: "auto" as const },
};
