import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  page: { display: "flex", flexDirection: "column", gap: 14, height: "100%" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap" as const },
  titleWrap: { display: "flex", flexDirection: "column", gap: 4 },
  title: { margin: 0, fontSize: 22, fontWeight: 800, color: "#f3f6fb" },
  subtitle: { fontSize: 13, color: "#97a0af", maxWidth: 720 },
  panel: { backgroundColor: "#252526", border: "1px solid #333841", borderRadius: 16, padding: 16 },
  headerControls: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" as const },
  select: {
    minWidth: 260,
    padding: "10px 12px",
    backgroundColor: "#181b20",
    border: "1px solid #3c4452",
    borderRadius: 10,
    color: "#eef2f8",
    fontSize: 13,
  },
  statusCard: {
    background: "linear-gradient(180deg, rgba(18,34,58,0.95), rgba(18,29,42,0.95))",
    border: "1px solid #2f4969",
    borderRadius: 16,
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  statusTitle: { fontSize: 18, fontWeight: 800, color: "#f4f8ff" },
  statusBody: { fontSize: 14, color: "#c7d3e3", lineHeight: 1.45 },
  chips: { display: "flex", gap: 8, flexWrap: "wrap" as const },
  chip: { backgroundColor: "#223851", color: "#dce9ff", borderRadius: 999, padding: "4px 10px", fontSize: 12, fontWeight: 700 },
  btn: {
    padding: "11px 16px",
    fontSize: 14,
    backgroundColor: "#0e639c",
    color: "#fff",
    border: "none",
    borderRadius: 10,
    cursor: "pointer",
    fontWeight: 800,
  },
  btnGhost: {
    padding: "11px 16px",
    fontSize: 14,
    backgroundColor: "#2d323a",
    color: "#e0e5ee",
    border: "1px solid #3f4754",
    borderRadius: 10,
    cursor: "pointer",
    fontWeight: 800,
  },
  btnDanger: {
    padding: "11px 16px",
    fontSize: 14,
    backgroundColor: "#7d2a2a",
    color: "#fff",
    border: "none",
    borderRadius: 10,
    cursor: "pointer",
    fontWeight: 800,
  },
  transcript: {
    backgroundColor: "#171a20",
    border: "1px solid #313846",
    borderRadius: 14,
    padding: 14,
    minHeight: 84,
    color: "#edf2fa",
    fontSize: 15,
    lineHeight: 1.45,
  },
  conversation: {
    flex: 1,
    minHeight: 0,
    backgroundColor: "#212327",
    border: "1px solid #32353d",
    borderRadius: 16,
    padding: 14,
    overflowY: "auto" as const,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  bubbleUser: {
    alignSelf: "flex-end",
    maxWidth: "78%",
    backgroundColor: "#0e639c",
    borderRadius: 14,
    padding: "11px 13px",
    color: "#fff",
    whiteSpace: "pre-wrap" as const,
  },
  bubbleAssistant: {
    alignSelf: "flex-start",
    maxWidth: "85%",
    backgroundColor: "#2b2f37",
    borderRadius: 14,
    padding: "11px 13px",
    color: "#e9edf6",
    whiteSpace: "pre-wrap" as const,
  },
  bubbleMeta: { fontSize: 11, color: "#8f96a3", marginBottom: 4, fontWeight: 700, textTransform: "uppercase" as const },
  error: { color: "#ff8d8d", fontSize: 13 },
  helper: { color: "#8f96a3", fontSize: 12 },
  composer: { display: "flex", gap: 10, alignItems: "stretch" },
  textarea: {
    flex: 1,
    minHeight: 74,
    padding: "10px 12px",
    backgroundColor: "#181a1f",
    border: "1px solid #3c4048",
    borderRadius: 12,
    color: "#e0e0e0",
    resize: "vertical" as const,
    fontSize: 13,
  },
  footerActions: { display: "flex", flexDirection: "column", gap: 8 },
};
